namespace TEN.Serialization.Config;

table Binding {
	action_id: int32;
	key_id: int32;
}

table Configuration {
	bindings: [Binding];
	enable_tank_camera_control: bool;
	invert_camera_x_axis: bool;
	invert_camera_y_axis: bool;
	enable_rumble: bool;
	mouse_sensitivity: int32;
	menu_option_looping_mode: int32;
	last_gamepad_type: int32;

	control_mode: int32;
	swim_control_mode: int32;
	enable_walk_toggle: bool;
	enable_crouch_toggle: bool;
	enable_climb_toggle: bool;
	enable_auto_monkey_swing_jump: bool;
	enable_auto_targeting: bool;
	enable_opposite_action_roll: bool;
	enable_target_highlighter: bool;
	enable_interaction_highlighter: bool;
	enable_subtitles: bool;
	
	screen_width: int32;
	screen_height: int32;
	gamma: float;
	enable_windowed_mode: bool;
	shadow_mode: int32;
	shadow_map_size: int32;
	shadow_blob_count_max: int32;
	enable_caustics: bool;
	enable_decals: bool;
	enable_ambient_occlusion: bool;
	enable_high_framerate: bool;
	antialiasing_mode: int32;

	sound_device: int32;
	enable_reverb: bool;
	music_volume: int32;
	sfx_volume: int32;

	adapter_name: string;
}

root_type Configuration;
