// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TENITEMDATA_TEN_SAVE_H_
#define FLATBUFFERS_GENERATED_TENITEMDATA_TEN_SAVE_H_

#include "flatbuffers/flatbuffers.h"

namespace TEN {
namespace Save {

struct Short;
struct ShortBuilder;

struct Int;
struct IntBuilder;

struct Float;
struct FloatBuilder;

struct ShortArray;
struct ShortArrayBuilder;

struct EulerAngles;

struct Vector2;

struct Vector3;

struct Vector4;

struct GameVector;

struct Pose;

struct BadBox;
struct BadBoxBuilder;

struct CreatureTarget;
struct CreatureTargetBuilder;

struct Creature;
struct CreatureBuilder;

struct LaserHead;
struct LaserHeadBuilder;

struct QuadBike;
struct QuadBikeBuilder;

struct BigGun;
struct BigGunBuilder;

struct Motorbike;
struct MotorbikeBuilder;

struct Jeep;
struct JeepBuilder;

struct Kayak;
struct KayakBuilder;

struct Door;
struct DoorBuilder;

struct Skidoo;
struct SkidooBuilder;

struct UPV;
struct UPVBuilder;

struct Motorboat;
struct MotorboatBuilder;

struct Wraith;
struct WraithBuilder;

struct Rubberboat;
struct RubberboatBuilder;

struct Pushable;
struct PushableBuilder;

struct Minecart;
struct MinecartBuilder;

struct LaraInfo;
struct LaraInfoBuilder;

struct ItemNumber;
struct ItemNumberBuilder;

struct FXInfo;
struct FXInfoBuilder;

enum ItemData : uint8_t {
  ItemData_NONE = 0,
  ItemData_Int = 1,
  ItemData_Short = 2,
  ItemData_Float = 3,
  ItemData_ShortArray = 4,
  ItemData_ItemNumber = 5,
  ItemData_Creature = 6,
  ItemData_LaserHead = 7,
  ItemData_QuadBike = 8,
  ItemData_BigGun = 9,
  ItemData_Motorbike = 10,
  ItemData_Jeep = 11,
  ItemData_LaraInfo = 12,
  ItemData_Kayak = 13,
  ItemData_Door = 14,
  ItemData_Skidoo = 15,
  ItemData_UPV = 16,
  ItemData_Motorboat = 17,
  ItemData_Wraith = 18,
  ItemData_Rubberboat = 19,
  ItemData_Pushable = 20,
  ItemData_Minecart = 21,
  ItemData_FXInfo = 22,
  ItemData_MIN = ItemData_NONE,
  ItemData_MAX = ItemData_FXInfo
};

inline const ItemData (&EnumValuesItemData())[23] {
  static const ItemData values[] = {
    ItemData_NONE,
    ItemData_Int,
    ItemData_Short,
    ItemData_Float,
    ItemData_ShortArray,
    ItemData_ItemNumber,
    ItemData_Creature,
    ItemData_LaserHead,
    ItemData_QuadBike,
    ItemData_BigGun,
    ItemData_Motorbike,
    ItemData_Jeep,
    ItemData_LaraInfo,
    ItemData_Kayak,
    ItemData_Door,
    ItemData_Skidoo,
    ItemData_UPV,
    ItemData_Motorboat,
    ItemData_Wraith,
    ItemData_Rubberboat,
    ItemData_Pushable,
    ItemData_Minecart,
    ItemData_FXInfo
  };
  return values;
}

inline const char * const *EnumNamesItemData() {
  static const char * const names[24] = {
    "NONE",
    "Int",
    "Short",
    "Float",
    "ShortArray",
    "ItemNumber",
    "Creature",
    "LaserHead",
    "QuadBike",
    "BigGun",
    "Motorbike",
    "Jeep",
    "LaraInfo",
    "Kayak",
    "Door",
    "Skidoo",
    "UPV",
    "Motorboat",
    "Wraith",
    "Rubberboat",
    "Pushable",
    "Minecart",
    "FXInfo",
    nullptr
  };
  return names;
}

inline const char *EnumNameItemData(ItemData e) {
  if (flatbuffers::IsOutRange(e, ItemData_NONE, ItemData_FXInfo)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesItemData()[index];
}

template<typename T> struct ItemDataTraits {
  static const ItemData enum_value = ItemData_NONE;
};

template<> struct ItemDataTraits<TEN::Save::Int> {
  static const ItemData enum_value = ItemData_Int;
};

template<> struct ItemDataTraits<TEN::Save::Short> {
  static const ItemData enum_value = ItemData_Short;
};

template<> struct ItemDataTraits<TEN::Save::Float> {
  static const ItemData enum_value = ItemData_Float;
};

template<> struct ItemDataTraits<TEN::Save::ShortArray> {
  static const ItemData enum_value = ItemData_ShortArray;
};

template<> struct ItemDataTraits<TEN::Save::ItemNumber> {
  static const ItemData enum_value = ItemData_ItemNumber;
};

template<> struct ItemDataTraits<TEN::Save::Creature> {
  static const ItemData enum_value = ItemData_Creature;
};

template<> struct ItemDataTraits<TEN::Save::LaserHead> {
  static const ItemData enum_value = ItemData_LaserHead;
};

template<> struct ItemDataTraits<TEN::Save::QuadBike> {
  static const ItemData enum_value = ItemData_QuadBike;
};

template<> struct ItemDataTraits<TEN::Save::BigGun> {
  static const ItemData enum_value = ItemData_BigGun;
};

template<> struct ItemDataTraits<TEN::Save::Motorbike> {
  static const ItemData enum_value = ItemData_Motorbike;
};

template<> struct ItemDataTraits<TEN::Save::Jeep> {
  static const ItemData enum_value = ItemData_Jeep;
};

template<> struct ItemDataTraits<TEN::Save::LaraInfo> {
  static const ItemData enum_value = ItemData_LaraInfo;
};

template<> struct ItemDataTraits<TEN::Save::Kayak> {
  static const ItemData enum_value = ItemData_Kayak;
};

template<> struct ItemDataTraits<TEN::Save::Door> {
  static const ItemData enum_value = ItemData_Door;
};

template<> struct ItemDataTraits<TEN::Save::Skidoo> {
  static const ItemData enum_value = ItemData_Skidoo;
};

template<> struct ItemDataTraits<TEN::Save::UPV> {
  static const ItemData enum_value = ItemData_UPV;
};

template<> struct ItemDataTraits<TEN::Save::Motorboat> {
  static const ItemData enum_value = ItemData_Motorboat;
};

template<> struct ItemDataTraits<TEN::Save::Wraith> {
  static const ItemData enum_value = ItemData_Wraith;
};

template<> struct ItemDataTraits<TEN::Save::Rubberboat> {
  static const ItemData enum_value = ItemData_Rubberboat;
};

template<> struct ItemDataTraits<TEN::Save::Pushable> {
  static const ItemData enum_value = ItemData_Pushable;
};

template<> struct ItemDataTraits<TEN::Save::Minecart> {
  static const ItemData enum_value = ItemData_Minecart;
};

template<> struct ItemDataTraits<TEN::Save::FXInfo> {
  static const ItemData enum_value = ItemData_FXInfo;
};

bool VerifyItemData(flatbuffers::Verifier &verifier, const void *obj, ItemData type);
bool VerifyItemDataVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) EulerAngles FLATBUFFERS_FINAL_CLASS {
 private:
  int16_t x_;
  int16_t y_;
  int16_t z_;

 public:
  EulerAngles()
      : x_(0),
        y_(0),
        z_(0) {
  }
  EulerAngles(int16_t _x, int16_t _y, int16_t _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  int16_t x() const {
    return flatbuffers::EndianScalar(x_);
  }
  int16_t y() const {
    return flatbuffers::EndianScalar(y_);
  }
  int16_t z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(EulerAngles, 6);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vector2()
      : x_(0),
        y_(0) {
  }
  Vector2(float _x, float _y)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vector2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vector3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vector3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vector3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vector4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vector4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vector4(float _x, float _y, float _z, float _w)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        w_(flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vector4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) GameVector FLATBUFFERS_FINAL_CLASS {
 private:
  int32_t x_;
  int32_t y_;
  int32_t z_;
  int32_t room_number_;

 public:
  GameVector()
      : x_(0),
        y_(0),
        z_(0),
        room_number_(0) {
  }
  GameVector(int32_t _x, int32_t _y, int32_t _z, int32_t _room_number)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)),
        room_number_(flatbuffers::EndianScalar(_room_number)) {
  }
  int32_t x() const {
    return flatbuffers::EndianScalar(x_);
  }
  int32_t y() const {
    return flatbuffers::EndianScalar(y_);
  }
  int32_t z() const {
    return flatbuffers::EndianScalar(z_);
  }
  int32_t room_number() const {
    return flatbuffers::EndianScalar(room_number_);
  }
};
FLATBUFFERS_STRUCT_END(GameVector, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Pose FLATBUFFERS_FINAL_CLASS {
 private:
  TEN::Save::Vector3 position_;
  TEN::Save::EulerAngles orientation_;
  int16_t padding0__;
  TEN::Save::Vector3 scale_;

 public:
  Pose()
      : position_(),
        orientation_(),
        padding0__(0),
        scale_() {
    (void)padding0__;
  }
  Pose(const TEN::Save::Vector3 &_position, const TEN::Save::EulerAngles &_orientation, const TEN::Save::Vector3 &_scale)
      : position_(_position),
        orientation_(_orientation),
        padding0__(0),
        scale_(_scale) {
    (void)padding0__;
  }
  const TEN::Save::Vector3 &position() const {
    return position_;
  }
  const TEN::Save::EulerAngles &orientation() const {
    return orientation_;
  }
  const TEN::Save::Vector3 &scale() const {
    return scale_;
  }
};
FLATBUFFERS_STRUCT_END(Pose, 32);

struct Short FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ShortBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCALAR = 4
  };
  int16_t scalar() const {
    return GetField<int16_t>(VT_SCALAR, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_SCALAR) &&
           verifier.EndTable();
  }
};

struct ShortBuilder {
  typedef Short Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_scalar(int16_t scalar) {
    fbb_.AddElement<int16_t>(Short::VT_SCALAR, scalar, 0);
  }
  explicit ShortBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Short> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Short>(end);
    return o;
  }
};

inline flatbuffers::Offset<Short> CreateShort(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t scalar = 0) {
  ShortBuilder builder_(_fbb);
  builder_.add_scalar(scalar);
  return builder_.Finish();
}

struct Int FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef IntBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCALAR = 4
  };
  int32_t scalar() const {
    return GetField<int32_t>(VT_SCALAR, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_SCALAR) &&
           verifier.EndTable();
  }
};

struct IntBuilder {
  typedef Int Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_scalar(int32_t scalar) {
    fbb_.AddElement<int32_t>(Int::VT_SCALAR, scalar, 0);
  }
  explicit IntBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Int> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Int>(end);
    return o;
  }
};

inline flatbuffers::Offset<Int> CreateInt(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t scalar = 0) {
  IntBuilder builder_(_fbb);
  builder_.add_scalar(scalar);
  return builder_.Finish();
}

struct Float FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FloatBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCALAR = 4
  };
  double scalar() const {
    return GetField<double>(VT_SCALAR, 0.0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<double>(verifier, VT_SCALAR) &&
           verifier.EndTable();
  }
};

struct FloatBuilder {
  typedef Float Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_scalar(double scalar) {
    fbb_.AddElement<double>(Float::VT_SCALAR, scalar, 0.0);
  }
  explicit FloatBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Float> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Float>(end);
    return o;
  }
};

inline flatbuffers::Offset<Float> CreateFloat(
    flatbuffers::FlatBufferBuilder &_fbb,
    double scalar = 0.0) {
  FloatBuilder builder_(_fbb);
  builder_.add_scalar(scalar);
  return builder_.Finish();
}

struct ShortArray FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ShortArrayBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ARR = 4
  };
  const flatbuffers::Vector<int16_t> *arr() const {
    return GetPointer<const flatbuffers::Vector<int16_t> *>(VT_ARR);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ARR) &&
           verifier.VerifyVector(arr()) &&
           verifier.EndTable();
  }
};

struct ShortArrayBuilder {
  typedef ShortArray Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_arr(flatbuffers::Offset<flatbuffers::Vector<int16_t>> arr) {
    fbb_.AddOffset(ShortArray::VT_ARR, arr);
  }
  explicit ShortArrayBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ShortArray> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ShortArray>(end);
    return o;
  }
};

inline flatbuffers::Offset<ShortArray> CreateShortArray(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<int16_t>> arr = 0) {
  ShortArrayBuilder builder_(_fbb);
  builder_.add_arr(arr);
  return builder_.Finish();
}

inline flatbuffers::Offset<ShortArray> CreateShortArrayDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<int16_t> *arr = nullptr) {
  auto arr__ = arr ? _fbb.CreateVector<int16_t>(*arr) : 0;
  return TEN::Save::CreateShortArray(
      _fbb,
      arr__);
}

struct BadBox FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef BadBoxBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALID = 4,
    VT_BOX_NUMBER = 6,
    VT_COUNT = 8
  };
  bool valid() const {
    return GetField<uint8_t>(VT_VALID, 0) != 0;
  }
  int32_t box_number() const {
    return GetField<int32_t>(VT_BOX_NUMBER, 0);
  }
  int32_t count() const {
    return GetField<int32_t>(VT_COUNT, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_VALID) &&
           VerifyField<int32_t>(verifier, VT_BOX_NUMBER) &&
           VerifyField<int32_t>(verifier, VT_COUNT) &&
           verifier.EndTable();
  }
};

struct BadBoxBuilder {
  typedef BadBox Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_valid(bool valid) {
    fbb_.AddElement<uint8_t>(BadBox::VT_VALID, static_cast<uint8_t>(valid), 0);
  }
  void add_box_number(int32_t box_number) {
    fbb_.AddElement<int32_t>(BadBox::VT_BOX_NUMBER, box_number, 0);
  }
  void add_count(int32_t count) {
    fbb_.AddElement<int32_t>(BadBox::VT_COUNT, count, 0);
  }
  explicit BadBoxBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<BadBox> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<BadBox>(end);
    return o;
  }
};

inline flatbuffers::Offset<BadBox> CreateBadBox(
    flatbuffers::FlatBufferBuilder &_fbb,
    bool valid = false,
    int32_t box_number = 0,
    int32_t count = 0) {
  BadBoxBuilder builder_(_fbb);
  builder_.add_count(count);
  builder_.add_box_number(box_number);
  builder_.add_valid(valid);
  return builder_.Finish();
}

struct CreatureTarget FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CreatureTargetBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_OBJECT_NUMBER = 4,
    VT_ROOM_NUMBER = 6,
    VT_BOX_NUMBER = 8,
    VT_FLAGS = 10,
    VT_TRIGGER_FLAGS = 12,
    VT_POSITION = 14
  };
  int32_t object_number() const {
    return GetField<int32_t>(VT_OBJECT_NUMBER, 0);
  }
  int32_t room_number() const {
    return GetField<int32_t>(VT_ROOM_NUMBER, 0);
  }
  int32_t box_number() const {
    return GetField<int32_t>(VT_BOX_NUMBER, 0);
  }
  int32_t flags() const {
    return GetField<int32_t>(VT_FLAGS, 0);
  }
  int32_t trigger_flags() const {
    return GetField<int32_t>(VT_TRIGGER_FLAGS, 0);
  }
  const TEN::Save::Pose *position() const {
    return GetStruct<const TEN::Save::Pose *>(VT_POSITION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_OBJECT_NUMBER) &&
           VerifyField<int32_t>(verifier, VT_ROOM_NUMBER) &&
           VerifyField<int32_t>(verifier, VT_BOX_NUMBER) &&
           VerifyField<int32_t>(verifier, VT_FLAGS) &&
           VerifyField<int32_t>(verifier, VT_TRIGGER_FLAGS) &&
           VerifyField<TEN::Save::Pose>(verifier, VT_POSITION) &&
           verifier.EndTable();
  }
};

struct CreatureTargetBuilder {
  typedef CreatureTarget Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_object_number(int32_t object_number) {
    fbb_.AddElement<int32_t>(CreatureTarget::VT_OBJECT_NUMBER, object_number, 0);
  }
  void add_room_number(int32_t room_number) {
    fbb_.AddElement<int32_t>(CreatureTarget::VT_ROOM_NUMBER, room_number, 0);
  }
  void add_box_number(int32_t box_number) {
    fbb_.AddElement<int32_t>(CreatureTarget::VT_BOX_NUMBER, box_number, 0);
  }
  void add_flags(int32_t flags) {
    fbb_.AddElement<int32_t>(CreatureTarget::VT_FLAGS, flags, 0);
  }
  void add_trigger_flags(int32_t trigger_flags) {
    fbb_.AddElement<int32_t>(CreatureTarget::VT_TRIGGER_FLAGS, trigger_flags, 0);
  }
  void add_position(const TEN::Save::Pose *position) {
    fbb_.AddStruct(CreatureTarget::VT_POSITION, position);
  }
  explicit CreatureTargetBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<CreatureTarget> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<CreatureTarget>(end);
    return o;
  }
};

inline flatbuffers::Offset<CreatureTarget> CreateCreatureTarget(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t object_number = 0,
    int32_t room_number = 0,
    int32_t box_number = 0,
    int32_t flags = 0,
    int32_t trigger_flags = 0,
    const TEN::Save::Pose *position = 0) {
  CreatureTargetBuilder builder_(_fbb);
  builder_.add_position(position);
  builder_.add_trigger_flags(trigger_flags);
  builder_.add_flags(flags);
  builder_.add_box_number(box_number);
  builder_.add_room_number(room_number);
  builder_.add_object_number(object_number);
  return builder_.Finish();
}

struct Creature FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef CreatureBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FLY_RATE = 4,
    VT_MAXIMUM_TURN = 6,
    VT_JOINT_ROTATION = 8,
    VT_HEAD_LEFT = 10,
    VT_HEAD_RIGHT = 12,
    VT_PATROL = 14,
    VT_ALERTED = 16,
    VT_REACHED_GOAL = 18,
    VT_JUMP_AHEAD = 20,
    VT_MONKEY_SWING_AHEAD = 22,
    VT_FRIENDLY = 24,
    VT_POISONED = 26,
    VT_HURT_BY_LARA = 28,
    VT_TOSSPAD = 30,
    VT_LOCATION_AI = 32,
    VT_WEAPON_DELAY1 = 34,
    VT_WEAPON_DELAY2 = 36,
    VT_MOOD = 38,
    VT_ENEMY = 40,
    VT_AI_TARGET_NUMBER = 42,
    VT_FLAGS = 44,
    VT_CAN_JUMP = 46,
    VT_CAN_MONKEY = 48,
    VT_IS_JUMPING = 50,
    VT_IS_MONKEYING = 52,
    VT_BAD_BOXES = 54
  };
  int32_t fly_rate() const {
    return GetField<int32_t>(VT_FLY_RATE, 0);
  }
  int32_t maximum_turn() const {
    return GetField<int32_t>(VT_MAXIMUM_TURN, 0);
  }
  const flatbuffers::Vector<int32_t> *joint_rotation() const {
    return GetPointer<const flatbuffers::Vector<int32_t> *>(VT_JOINT_ROTATION);
  }
  bool head_left() const {
    return GetField<uint8_t>(VT_HEAD_LEFT, 0) != 0;
  }
  bool head_right() const {
    return GetField<uint8_t>(VT_HEAD_RIGHT, 0) != 0;
  }
  bool patrol() const {
    return GetField<uint8_t>(VT_PATROL, 0) != 0;
  }
  bool alerted() const {
    return GetField<uint8_t>(VT_ALERTED, 0) != 0;
  }
  bool reached_goal() const {
    return GetField<uint8_t>(VT_REACHED_GOAL, 0) != 0;
  }
  bool jump_ahead() const {
    return GetField<uint8_t>(VT_JUMP_AHEAD, 0) != 0;
  }
  bool monkey_swing_ahead() const {
    return GetField<uint8_t>(VT_MONKEY_SWING_AHEAD, 0) != 0;
  }
  bool friendly() const {
    return GetField<uint8_t>(VT_FRIENDLY, 0) != 0;
  }
  bool poisoned() const {
    return GetField<uint8_t>(VT_POISONED, 0) != 0;
  }
  bool hurt_by_lara() const {
    return GetField<uint8_t>(VT_HURT_BY_LARA, 0) != 0;
  }
  int32_t tosspad() const {
    return GetField<int32_t>(VT_TOSSPAD, 0);
  }
  int32_t location_ai() const {
    return GetField<int32_t>(VT_LOCATION_AI, 0);
  }
  int32_t weapon_delay1() const {
    return GetField<int32_t>(VT_WEAPON_DELAY1, 0);
  }
  int32_t weapon_delay2() const {
    return GetField<int32_t>(VT_WEAPON_DELAY2, 0);
  }
  int32_t mood() const {
    return GetField<int32_t>(VT_MOOD, 0);
  }
  int32_t enemy() const {
    return GetField<int32_t>(VT_ENEMY, 0);
  }
  int32_t ai_target_number() const {
    return GetField<int32_t>(VT_AI_TARGET_NUMBER, 0);
  }
  int32_t flags() const {
    return GetField<int32_t>(VT_FLAGS, 0);
  }
  bool can_jump() const {
    return GetField<uint8_t>(VT_CAN_JUMP, 0) != 0;
  }
  bool can_monkey() const {
    return GetField<uint8_t>(VT_CAN_MONKEY, 0) != 0;
  }
  bool is_jumping() const {
    return GetField<uint8_t>(VT_IS_JUMPING, 0) != 0;
  }
  bool is_monkeying() const {
    return GetField<uint8_t>(VT_IS_MONKEYING, 0) != 0;
  }
  const flatbuffers::Vector<flatbuffers::Offset<TEN::Save::BadBox>> *bad_boxes() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<TEN::Save::BadBox>> *>(VT_BAD_BOXES);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_FLY_RATE) &&
           VerifyField<int32_t>(verifier, VT_MAXIMUM_TURN) &&
           VerifyOffset(verifier, VT_JOINT_ROTATION) &&
           verifier.VerifyVector(joint_rotation()) &&
           VerifyField<uint8_t>(verifier, VT_HEAD_LEFT) &&
           VerifyField<uint8_t>(verifier, VT_HEAD_RIGHT) &&
           VerifyField<uint8_t>(verifier, VT_PATROL) &&
           VerifyField<uint8_t>(verifier, VT_ALERTED) &&
           VerifyField<uint8_t>(verifier, VT_REACHED_GOAL) &&
           VerifyField<uint8_t>(verifier, VT_JUMP_AHEAD) &&
           VerifyField<uint8_t>(verifier, VT_MONKEY_SWING_AHEAD) &&
           VerifyField<uint8_t>(verifier, VT_FRIENDLY) &&
           VerifyField<uint8_t>(verifier, VT_POISONED) &&
           VerifyField<uint8_t>(verifier, VT_HURT_BY_LARA) &&
           VerifyField<int32_t>(verifier, VT_TOSSPAD) &&
           VerifyField<int32_t>(verifier, VT_LOCATION_AI) &&
           VerifyField<int32_t>(verifier, VT_WEAPON_DELAY1) &&
           VerifyField<int32_t>(verifier, VT_WEAPON_DELAY2) &&
           VerifyField<int32_t>(verifier, VT_MOOD) &&
           VerifyField<int32_t>(verifier, VT_ENEMY) &&
           VerifyField<int32_t>(verifier, VT_AI_TARGET_NUMBER) &&
           VerifyField<int32_t>(verifier, VT_FLAGS) &&
           VerifyField<uint8_t>(verifier, VT_CAN_JUMP) &&
           VerifyField<uint8_t>(verifier, VT_CAN_MONKEY) &&
           VerifyField<uint8_t>(verifier, VT_IS_JUMPING) &&
           VerifyField<uint8_t>(verifier, VT_IS_MONKEYING) &&
           VerifyOffset(verifier, VT_BAD_BOXES) &&
           verifier.VerifyVector(bad_boxes()) &&
           verifier.VerifyVectorOfTables(bad_boxes()) &&
           verifier.EndTable();
  }
};

struct CreatureBuilder {
  typedef Creature Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_fly_rate(int32_t fly_rate) {
    fbb_.AddElement<int32_t>(Creature::VT_FLY_RATE, fly_rate, 0);
  }
  void add_maximum_turn(int32_t maximum_turn) {
    fbb_.AddElement<int32_t>(Creature::VT_MAXIMUM_TURN, maximum_turn, 0);
  }
  void add_joint_rotation(flatbuffers::Offset<flatbuffers::Vector<int32_t>> joint_rotation) {
    fbb_.AddOffset(Creature::VT_JOINT_ROTATION, joint_rotation);
  }
  void add_head_left(bool head_left) {
    fbb_.AddElement<uint8_t>(Creature::VT_HEAD_LEFT, static_cast<uint8_t>(head_left), 0);
  }
  void add_head_right(bool head_right) {
    fbb_.AddElement<uint8_t>(Creature::VT_HEAD_RIGHT, static_cast<uint8_t>(head_right), 0);
  }
  void add_patrol(bool patrol) {
    fbb_.AddElement<uint8_t>(Creature::VT_PATROL, static_cast<uint8_t>(patrol), 0);
  }
  void add_alerted(bool alerted) {
    fbb_.AddElement<uint8_t>(Creature::VT_ALERTED, static_cast<uint8_t>(alerted), 0);
  }
  void add_reached_goal(bool reached_goal) {
    fbb_.AddElement<uint8_t>(Creature::VT_REACHED_GOAL, static_cast<uint8_t>(reached_goal), 0);
  }
  void add_jump_ahead(bool jump_ahead) {
    fbb_.AddElement<uint8_t>(Creature::VT_JUMP_AHEAD, static_cast<uint8_t>(jump_ahead), 0);
  }
  void add_monkey_swing_ahead(bool monkey_swing_ahead) {
    fbb_.AddElement<uint8_t>(Creature::VT_MONKEY_SWING_AHEAD, static_cast<uint8_t>(monkey_swing_ahead), 0);
  }
  void add_friendly(bool friendly) {
    fbb_.AddElement<uint8_t>(Creature::VT_FRIENDLY, static_cast<uint8_t>(friendly), 0);
  }
  void add_poisoned(bool poisoned) {
    fbb_.AddElement<uint8_t>(Creature::VT_POISONED, static_cast<uint8_t>(poisoned), 0);
  }
  void add_hurt_by_lara(bool hurt_by_lara) {
    fbb_.AddElement<uint8_t>(Creature::VT_HURT_BY_LARA, static_cast<uint8_t>(hurt_by_lara), 0);
  }
  void add_tosspad(int32_t tosspad) {
    fbb_.AddElement<int32_t>(Creature::VT_TOSSPAD, tosspad, 0);
  }
  void add_location_ai(int32_t location_ai) {
    fbb_.AddElement<int32_t>(Creature::VT_LOCATION_AI, location_ai, 0);
  }
  void add_weapon_delay1(int32_t weapon_delay1) {
    fbb_.AddElement<int32_t>(Creature::VT_WEAPON_DELAY1, weapon_delay1, 0);
  }
  void add_weapon_delay2(int32_t weapon_delay2) {
    fbb_.AddElement<int32_t>(Creature::VT_WEAPON_DELAY2, weapon_delay2, 0);
  }
  void add_mood(int32_t mood) {
    fbb_.AddElement<int32_t>(Creature::VT_MOOD, mood, 0);
  }
  void add_enemy(int32_t enemy) {
    fbb_.AddElement<int32_t>(Creature::VT_ENEMY, enemy, 0);
  }
  void add_ai_target_number(int32_t ai_target_number) {
    fbb_.AddElement<int32_t>(Creature::VT_AI_TARGET_NUMBER, ai_target_number, 0);
  }
  void add_flags(int32_t flags) {
    fbb_.AddElement<int32_t>(Creature::VT_FLAGS, flags, 0);
  }
  void add_can_jump(bool can_jump) {
    fbb_.AddElement<uint8_t>(Creature::VT_CAN_JUMP, static_cast<uint8_t>(can_jump), 0);
  }
  void add_can_monkey(bool can_monkey) {
    fbb_.AddElement<uint8_t>(Creature::VT_CAN_MONKEY, static_cast<uint8_t>(can_monkey), 0);
  }
  void add_is_jumping(bool is_jumping) {
    fbb_.AddElement<uint8_t>(Creature::VT_IS_JUMPING, static_cast<uint8_t>(is_jumping), 0);
  }
  void add_is_monkeying(bool is_monkeying) {
    fbb_.AddElement<uint8_t>(Creature::VT_IS_MONKEYING, static_cast<uint8_t>(is_monkeying), 0);
  }
  void add_bad_boxes(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TEN::Save::BadBox>>> bad_boxes) {
    fbb_.AddOffset(Creature::VT_BAD_BOXES, bad_boxes);
  }
  explicit CreatureBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Creature> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Creature>(end);
    return o;
  }
};

inline flatbuffers::Offset<Creature> CreateCreature(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t fly_rate = 0,
    int32_t maximum_turn = 0,
    flatbuffers::Offset<flatbuffers::Vector<int32_t>> joint_rotation = 0,
    bool head_left = false,
    bool head_right = false,
    bool patrol = false,
    bool alerted = false,
    bool reached_goal = false,
    bool jump_ahead = false,
    bool monkey_swing_ahead = false,
    bool friendly = false,
    bool poisoned = false,
    bool hurt_by_lara = false,
    int32_t tosspad = 0,
    int32_t location_ai = 0,
    int32_t weapon_delay1 = 0,
    int32_t weapon_delay2 = 0,
    int32_t mood = 0,
    int32_t enemy = 0,
    int32_t ai_target_number = 0,
    int32_t flags = 0,
    bool can_jump = false,
    bool can_monkey = false,
    bool is_jumping = false,
    bool is_monkeying = false,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<TEN::Save::BadBox>>> bad_boxes = 0) {
  CreatureBuilder builder_(_fbb);
  builder_.add_bad_boxes(bad_boxes);
  builder_.add_flags(flags);
  builder_.add_ai_target_number(ai_target_number);
  builder_.add_enemy(enemy);
  builder_.add_mood(mood);
  builder_.add_weapon_delay2(weapon_delay2);
  builder_.add_weapon_delay1(weapon_delay1);
  builder_.add_location_ai(location_ai);
  builder_.add_tosspad(tosspad);
  builder_.add_joint_rotation(joint_rotation);
  builder_.add_maximum_turn(maximum_turn);
  builder_.add_fly_rate(fly_rate);
  builder_.add_is_monkeying(is_monkeying);
  builder_.add_is_jumping(is_jumping);
  builder_.add_can_monkey(can_monkey);
  builder_.add_can_jump(can_jump);
  builder_.add_hurt_by_lara(hurt_by_lara);
  builder_.add_poisoned(poisoned);
  builder_.add_friendly(friendly);
  builder_.add_monkey_swing_ahead(monkey_swing_ahead);
  builder_.add_jump_ahead(jump_ahead);
  builder_.add_reached_goal(reached_goal);
  builder_.add_alerted(alerted);
  builder_.add_patrol(patrol);
  builder_.add_head_right(head_right);
  builder_.add_head_left(head_left);
  return builder_.Finish();
}

inline flatbuffers::Offset<Creature> CreateCreatureDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t fly_rate = 0,
    int32_t maximum_turn = 0,
    const std::vector<int32_t> *joint_rotation = nullptr,
    bool head_left = false,
    bool head_right = false,
    bool patrol = false,
    bool alerted = false,
    bool reached_goal = false,
    bool jump_ahead = false,
    bool monkey_swing_ahead = false,
    bool friendly = false,
    bool poisoned = false,
    bool hurt_by_lara = false,
    int32_t tosspad = 0,
    int32_t location_ai = 0,
    int32_t weapon_delay1 = 0,
    int32_t weapon_delay2 = 0,
    int32_t mood = 0,
    int32_t enemy = 0,
    int32_t ai_target_number = 0,
    int32_t flags = 0,
    bool can_jump = false,
    bool can_monkey = false,
    bool is_jumping = false,
    bool is_monkeying = false,
    const std::vector<flatbuffers::Offset<TEN::Save::BadBox>> *bad_boxes = nullptr) {
  auto joint_rotation__ = joint_rotation ? _fbb.CreateVector<int32_t>(*joint_rotation) : 0;
  auto bad_boxes__ = bad_boxes ? _fbb.CreateVector<flatbuffers::Offset<TEN::Save::BadBox>>(*bad_boxes) : 0;
  return TEN::Save::CreateCreature(
      _fbb,
      fly_rate,
      maximum_turn,
      joint_rotation__,
      head_left,
      head_right,
      patrol,
      alerted,
      reached_goal,
      jump_ahead,
      monkey_swing_ahead,
      friendly,
      poisoned,
      hurt_by_lara,
      tosspad,
      location_ai,
      weapon_delay1,
      weapon_delay2,
      mood,
      enemy,
      ai_target_number,
      flags,
      can_jump,
      can_monkey,
      is_jumping,
      is_monkeying,
      bad_boxes__);
}

struct LaserHead FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LaserHeadBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct LaserHeadBuilder {
  typedef LaserHead Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit LaserHeadBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<LaserHead> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LaserHead>(end);
    return o;
  }
};

inline flatbuffers::Offset<LaserHead> CreateLaserHead(
    flatbuffers::FlatBufferBuilder &_fbb) {
  LaserHeadBuilder builder_(_fbb);
  return builder_.Finish();
}

struct QuadBike FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef QuadBikeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TURN_RATE = 4,
    VT_FRONT_ROT = 6,
    VT_REAR_ROT = 8,
    VT_MOMENTUM_ANGLE = 10,
    VT_EXTRA_ROTATION = 12,
    VT_VELOCITY = 14,
    VT_LEFT_VERTICAL_VELOCITY = 16,
    VT_RIGHT_VERTICAL_VELOCITY = 18,
    VT_REVS = 20,
    VT_ENGINE_REVS = 22,
    VT_PITCH = 24,
    VT_SMOKE_START = 26,
    VT_CAN_START_DRIFT = 28,
    VT_DRIFT_STARTING = 30,
    VT_NO_DISMOUNT = 32,
    VT_FLAGS = 34
  };
  int32_t turn_rate() const {
    return GetField<int32_t>(VT_TURN_RATE, 0);
  }
  int32_t front_rot() const {
    return GetField<int32_t>(VT_FRONT_ROT, 0);
  }
  int32_t rear_rot() const {
    return GetField<int32_t>(VT_REAR_ROT, 0);
  }
  int32_t momentum_angle() const {
    return GetField<int32_t>(VT_MOMENTUM_ANGLE, 0);
  }
  int32_t extra_rotation() const {
    return GetField<int32_t>(VT_EXTRA_ROTATION, 0);
  }
  int32_t velocity() const {
    return GetField<int32_t>(VT_VELOCITY, 0);
  }
  int32_t left_vertical_velocity() const {
    return GetField<int32_t>(VT_LEFT_VERTICAL_VELOCITY, 0);
  }
  int32_t right_vertical_velocity() const {
    return GetField<int32_t>(VT_RIGHT_VERTICAL_VELOCITY, 0);
  }
  int32_t revs() const {
    return GetField<int32_t>(VT_REVS, 0);
  }
  int32_t engine_revs() const {
    return GetField<int32_t>(VT_ENGINE_REVS, 0);
  }
  int32_t pitch() const {
    return GetField<int32_t>(VT_PITCH, 0);
  }
  int32_t smoke_start() const {
    return GetField<int32_t>(VT_SMOKE_START, 0);
  }
  bool can_start_drift() const {
    return GetField<uint8_t>(VT_CAN_START_DRIFT, 0) != 0;
  }
  bool drift_starting() const {
    return GetField<uint8_t>(VT_DRIFT_STARTING, 0) != 0;
  }
  bool no_dismount() const {
    return GetField<uint8_t>(VT_NO_DISMOUNT, 0) != 0;
  }
  int32_t flags() const {
    return GetField<int32_t>(VT_FLAGS, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TURN_RATE) &&
           VerifyField<int32_t>(verifier, VT_FRONT_ROT) &&
           VerifyField<int32_t>(verifier, VT_REAR_ROT) &&
           VerifyField<int32_t>(verifier, VT_MOMENTUM_ANGLE) &&
           VerifyField<int32_t>(verifier, VT_EXTRA_ROTATION) &&
           VerifyField<int32_t>(verifier, VT_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_LEFT_VERTICAL_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_RIGHT_VERTICAL_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_REVS) &&
           VerifyField<int32_t>(verifier, VT_ENGINE_REVS) &&
           VerifyField<int32_t>(verifier, VT_PITCH) &&
           VerifyField<int32_t>(verifier, VT_SMOKE_START) &&
           VerifyField<uint8_t>(verifier, VT_CAN_START_DRIFT) &&
           VerifyField<uint8_t>(verifier, VT_DRIFT_STARTING) &&
           VerifyField<uint8_t>(verifier, VT_NO_DISMOUNT) &&
           VerifyField<int32_t>(verifier, VT_FLAGS) &&
           verifier.EndTable();
  }
};

struct QuadBikeBuilder {
  typedef QuadBike Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_turn_rate(int32_t turn_rate) {
    fbb_.AddElement<int32_t>(QuadBike::VT_TURN_RATE, turn_rate, 0);
  }
  void add_front_rot(int32_t front_rot) {
    fbb_.AddElement<int32_t>(QuadBike::VT_FRONT_ROT, front_rot, 0);
  }
  void add_rear_rot(int32_t rear_rot) {
    fbb_.AddElement<int32_t>(QuadBike::VT_REAR_ROT, rear_rot, 0);
  }
  void add_momentum_angle(int32_t momentum_angle) {
    fbb_.AddElement<int32_t>(QuadBike::VT_MOMENTUM_ANGLE, momentum_angle, 0);
  }
  void add_extra_rotation(int32_t extra_rotation) {
    fbb_.AddElement<int32_t>(QuadBike::VT_EXTRA_ROTATION, extra_rotation, 0);
  }
  void add_velocity(int32_t velocity) {
    fbb_.AddElement<int32_t>(QuadBike::VT_VELOCITY, velocity, 0);
  }
  void add_left_vertical_velocity(int32_t left_vertical_velocity) {
    fbb_.AddElement<int32_t>(QuadBike::VT_LEFT_VERTICAL_VELOCITY, left_vertical_velocity, 0);
  }
  void add_right_vertical_velocity(int32_t right_vertical_velocity) {
    fbb_.AddElement<int32_t>(QuadBike::VT_RIGHT_VERTICAL_VELOCITY, right_vertical_velocity, 0);
  }
  void add_revs(int32_t revs) {
    fbb_.AddElement<int32_t>(QuadBike::VT_REVS, revs, 0);
  }
  void add_engine_revs(int32_t engine_revs) {
    fbb_.AddElement<int32_t>(QuadBike::VT_ENGINE_REVS, engine_revs, 0);
  }
  void add_pitch(int32_t pitch) {
    fbb_.AddElement<int32_t>(QuadBike::VT_PITCH, pitch, 0);
  }
  void add_smoke_start(int32_t smoke_start) {
    fbb_.AddElement<int32_t>(QuadBike::VT_SMOKE_START, smoke_start, 0);
  }
  void add_can_start_drift(bool can_start_drift) {
    fbb_.AddElement<uint8_t>(QuadBike::VT_CAN_START_DRIFT, static_cast<uint8_t>(can_start_drift), 0);
  }
  void add_drift_starting(bool drift_starting) {
    fbb_.AddElement<uint8_t>(QuadBike::VT_DRIFT_STARTING, static_cast<uint8_t>(drift_starting), 0);
  }
  void add_no_dismount(bool no_dismount) {
    fbb_.AddElement<uint8_t>(QuadBike::VT_NO_DISMOUNT, static_cast<uint8_t>(no_dismount), 0);
  }
  void add_flags(int32_t flags) {
    fbb_.AddElement<int32_t>(QuadBike::VT_FLAGS, flags, 0);
  }
  explicit QuadBikeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<QuadBike> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<QuadBike>(end);
    return o;
  }
};

inline flatbuffers::Offset<QuadBike> CreateQuadBike(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t turn_rate = 0,
    int32_t front_rot = 0,
    int32_t rear_rot = 0,
    int32_t momentum_angle = 0,
    int32_t extra_rotation = 0,
    int32_t velocity = 0,
    int32_t left_vertical_velocity = 0,
    int32_t right_vertical_velocity = 0,
    int32_t revs = 0,
    int32_t engine_revs = 0,
    int32_t pitch = 0,
    int32_t smoke_start = 0,
    bool can_start_drift = false,
    bool drift_starting = false,
    bool no_dismount = false,
    int32_t flags = 0) {
  QuadBikeBuilder builder_(_fbb);
  builder_.add_flags(flags);
  builder_.add_smoke_start(smoke_start);
  builder_.add_pitch(pitch);
  builder_.add_engine_revs(engine_revs);
  builder_.add_revs(revs);
  builder_.add_right_vertical_velocity(right_vertical_velocity);
  builder_.add_left_vertical_velocity(left_vertical_velocity);
  builder_.add_velocity(velocity);
  builder_.add_extra_rotation(extra_rotation);
  builder_.add_momentum_angle(momentum_angle);
  builder_.add_rear_rot(rear_rot);
  builder_.add_front_rot(front_rot);
  builder_.add_turn_rate(turn_rate);
  builder_.add_no_dismount(no_dismount);
  builder_.add_drift_starting(drift_starting);
  builder_.add_can_start_drift(can_start_drift);
  return builder_.Finish();
}

struct BigGun FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef BigGunBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct BigGunBuilder {
  typedef BigGun Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit BigGunBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<BigGun> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<BigGun>(end);
    return o;
  }
};

inline flatbuffers::Offset<BigGun> CreateBigGun(
    flatbuffers::FlatBufferBuilder &_fbb) {
  BigGunBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Motorbike FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MotorbikeBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct MotorbikeBuilder {
  typedef Motorbike Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit MotorbikeBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Motorbike> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Motorbike>(end);
    return o;
  }
};

inline flatbuffers::Offset<Motorbike> CreateMotorbike(
    flatbuffers::FlatBufferBuilder &_fbb) {
  MotorbikeBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Jeep FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef JeepBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct JeepBuilder {
  typedef Jeep Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit JeepBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Jeep> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Jeep>(end);
    return o;
  }
};

inline flatbuffers::Offset<Jeep> CreateJeep(
    flatbuffers::FlatBufferBuilder &_fbb) {
  JeepBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Kayak FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef KayakBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TURN_RATE = 4,
    VT_VELOCITY = 6,
    VT_FRONT_VERTICAL_VELOCITY = 8,
    VT_LEFT_VERTICAL_VELOCITY = 10,
    VT_RIGHT_VERTICAL_VELOCITY = 12,
    VT_LEFT_RIGHT_COUNT = 14,
    VT_WATER_HEIGHT = 16,
    VT_OLD_POS = 18,
    VT_TURN = 20,
    VT_FORWARD = 22,
    VT_TRUE_WATER = 24,
    VT_FLAGS = 26
  };
  int32_t turn_rate() const {
    return GetField<int32_t>(VT_TURN_RATE, 0);
  }
  int32_t velocity() const {
    return GetField<int32_t>(VT_VELOCITY, 0);
  }
  int32_t front_vertical_velocity() const {
    return GetField<int32_t>(VT_FRONT_VERTICAL_VELOCITY, 0);
  }
  int32_t left_vertical_velocity() const {
    return GetField<int32_t>(VT_LEFT_VERTICAL_VELOCITY, 0);
  }
  int32_t right_vertical_velocity() const {
    return GetField<int32_t>(VT_RIGHT_VERTICAL_VELOCITY, 0);
  }
  int32_t left_right_count() const {
    return GetField<int32_t>(VT_LEFT_RIGHT_COUNT, 0);
  }
  int32_t water_height() const {
    return GetField<int32_t>(VT_WATER_HEIGHT, 0);
  }
  const TEN::Save::Pose *old_pos() const {
    return GetStruct<const TEN::Save::Pose *>(VT_OLD_POS);
  }
  bool turn() const {
    return GetField<uint8_t>(VT_TURN, 0) != 0;
  }
  bool forward() const {
    return GetField<uint8_t>(VT_FORWARD, 0) != 0;
  }
  bool true_water() const {
    return GetField<uint8_t>(VT_TRUE_WATER, 0) != 0;
  }
  int32_t flags() const {
    return GetField<int32_t>(VT_FLAGS, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TURN_RATE) &&
           VerifyField<int32_t>(verifier, VT_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_FRONT_VERTICAL_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_LEFT_VERTICAL_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_RIGHT_VERTICAL_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_LEFT_RIGHT_COUNT) &&
           VerifyField<int32_t>(verifier, VT_WATER_HEIGHT) &&
           VerifyField<TEN::Save::Pose>(verifier, VT_OLD_POS) &&
           VerifyField<uint8_t>(verifier, VT_TURN) &&
           VerifyField<uint8_t>(verifier, VT_FORWARD) &&
           VerifyField<uint8_t>(verifier, VT_TRUE_WATER) &&
           VerifyField<int32_t>(verifier, VT_FLAGS) &&
           verifier.EndTable();
  }
};

struct KayakBuilder {
  typedef Kayak Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_turn_rate(int32_t turn_rate) {
    fbb_.AddElement<int32_t>(Kayak::VT_TURN_RATE, turn_rate, 0);
  }
  void add_velocity(int32_t velocity) {
    fbb_.AddElement<int32_t>(Kayak::VT_VELOCITY, velocity, 0);
  }
  void add_front_vertical_velocity(int32_t front_vertical_velocity) {
    fbb_.AddElement<int32_t>(Kayak::VT_FRONT_VERTICAL_VELOCITY, front_vertical_velocity, 0);
  }
  void add_left_vertical_velocity(int32_t left_vertical_velocity) {
    fbb_.AddElement<int32_t>(Kayak::VT_LEFT_VERTICAL_VELOCITY, left_vertical_velocity, 0);
  }
  void add_right_vertical_velocity(int32_t right_vertical_velocity) {
    fbb_.AddElement<int32_t>(Kayak::VT_RIGHT_VERTICAL_VELOCITY, right_vertical_velocity, 0);
  }
  void add_left_right_count(int32_t left_right_count) {
    fbb_.AddElement<int32_t>(Kayak::VT_LEFT_RIGHT_COUNT, left_right_count, 0);
  }
  void add_water_height(int32_t water_height) {
    fbb_.AddElement<int32_t>(Kayak::VT_WATER_HEIGHT, water_height, 0);
  }
  void add_old_pos(const TEN::Save::Pose *old_pos) {
    fbb_.AddStruct(Kayak::VT_OLD_POS, old_pos);
  }
  void add_turn(bool turn) {
    fbb_.AddElement<uint8_t>(Kayak::VT_TURN, static_cast<uint8_t>(turn), 0);
  }
  void add_forward(bool forward) {
    fbb_.AddElement<uint8_t>(Kayak::VT_FORWARD, static_cast<uint8_t>(forward), 0);
  }
  void add_true_water(bool true_water) {
    fbb_.AddElement<uint8_t>(Kayak::VT_TRUE_WATER, static_cast<uint8_t>(true_water), 0);
  }
  void add_flags(int32_t flags) {
    fbb_.AddElement<int32_t>(Kayak::VT_FLAGS, flags, 0);
  }
  explicit KayakBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Kayak> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Kayak>(end);
    return o;
  }
};

inline flatbuffers::Offset<Kayak> CreateKayak(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t turn_rate = 0,
    int32_t velocity = 0,
    int32_t front_vertical_velocity = 0,
    int32_t left_vertical_velocity = 0,
    int32_t right_vertical_velocity = 0,
    int32_t left_right_count = 0,
    int32_t water_height = 0,
    const TEN::Save::Pose *old_pos = 0,
    bool turn = false,
    bool forward = false,
    bool true_water = false,
    int32_t flags = 0) {
  KayakBuilder builder_(_fbb);
  builder_.add_flags(flags);
  builder_.add_old_pos(old_pos);
  builder_.add_water_height(water_height);
  builder_.add_left_right_count(left_right_count);
  builder_.add_right_vertical_velocity(right_vertical_velocity);
  builder_.add_left_vertical_velocity(left_vertical_velocity);
  builder_.add_front_vertical_velocity(front_vertical_velocity);
  builder_.add_velocity(velocity);
  builder_.add_turn_rate(turn_rate);
  builder_.add_true_water(true_water);
  builder_.add_forward(forward);
  builder_.add_turn(turn);
  return builder_.Finish();
}

struct Door FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef DoorBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct DoorBuilder {
  typedef Door Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit DoorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Door> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Door>(end);
    return o;
  }
};

inline flatbuffers::Offset<Door> CreateDoor(
    flatbuffers::FlatBufferBuilder &_fbb) {
  DoorBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Skidoo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef SkidooBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct SkidooBuilder {
  typedef Skidoo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit SkidooBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Skidoo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Skidoo>(end);
    return o;
  }
};

inline flatbuffers::Offset<Skidoo> CreateSkidoo(
    flatbuffers::FlatBufferBuilder &_fbb) {
  SkidooBuilder builder_(_fbb);
  return builder_.Finish();
}

struct UPV FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef UPVBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VELOCITY = 4,
    VT_ROT = 6,
    VT_X_ROT = 8,
    VT_FAN_ROT = 10,
    VT_HARPOON_TIMER = 12,
    VT_HARPOON_LEFT = 14,
    VT_FLAGS = 16
  };
  int32_t velocity() const {
    return GetField<int32_t>(VT_VELOCITY, 0);
  }
  int32_t rot() const {
    return GetField<int32_t>(VT_ROT, 0);
  }
  int32_t x_rot() const {
    return GetField<int32_t>(VT_X_ROT, 0);
  }
  int32_t fan_rot() const {
    return GetField<int32_t>(VT_FAN_ROT, 0);
  }
  int32_t harpoon_timer() const {
    return GetField<int32_t>(VT_HARPOON_TIMER, 0);
  }
  bool harpoon_left() const {
    return GetField<uint8_t>(VT_HARPOON_LEFT, 0) != 0;
  }
  int32_t flags() const {
    return GetField<int32_t>(VT_FLAGS, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_ROT) &&
           VerifyField<int32_t>(verifier, VT_X_ROT) &&
           VerifyField<int32_t>(verifier, VT_FAN_ROT) &&
           VerifyField<int32_t>(verifier, VT_HARPOON_TIMER) &&
           VerifyField<uint8_t>(verifier, VT_HARPOON_LEFT) &&
           VerifyField<int32_t>(verifier, VT_FLAGS) &&
           verifier.EndTable();
  }
};

struct UPVBuilder {
  typedef UPV Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_velocity(int32_t velocity) {
    fbb_.AddElement<int32_t>(UPV::VT_VELOCITY, velocity, 0);
  }
  void add_rot(int32_t rot) {
    fbb_.AddElement<int32_t>(UPV::VT_ROT, rot, 0);
  }
  void add_x_rot(int32_t x_rot) {
    fbb_.AddElement<int32_t>(UPV::VT_X_ROT, x_rot, 0);
  }
  void add_fan_rot(int32_t fan_rot) {
    fbb_.AddElement<int32_t>(UPV::VT_FAN_ROT, fan_rot, 0);
  }
  void add_harpoon_timer(int32_t harpoon_timer) {
    fbb_.AddElement<int32_t>(UPV::VT_HARPOON_TIMER, harpoon_timer, 0);
  }
  void add_harpoon_left(bool harpoon_left) {
    fbb_.AddElement<uint8_t>(UPV::VT_HARPOON_LEFT, static_cast<uint8_t>(harpoon_left), 0);
  }
  void add_flags(int32_t flags) {
    fbb_.AddElement<int32_t>(UPV::VT_FLAGS, flags, 0);
  }
  explicit UPVBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<UPV> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<UPV>(end);
    return o;
  }
};

inline flatbuffers::Offset<UPV> CreateUPV(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t velocity = 0,
    int32_t rot = 0,
    int32_t x_rot = 0,
    int32_t fan_rot = 0,
    int32_t harpoon_timer = 0,
    bool harpoon_left = false,
    int32_t flags = 0) {
  UPVBuilder builder_(_fbb);
  builder_.add_flags(flags);
  builder_.add_harpoon_timer(harpoon_timer);
  builder_.add_fan_rot(fan_rot);
  builder_.add_x_rot(x_rot);
  builder_.add_rot(rot);
  builder_.add_velocity(velocity);
  builder_.add_harpoon_left(harpoon_left);
  return builder_.Finish();
}

struct Motorboat FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MotorboatBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct MotorboatBuilder {
  typedef Motorboat Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit MotorboatBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Motorboat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Motorboat>(end);
    return o;
  }
};

inline flatbuffers::Offset<Motorboat> CreateMotorboat(
    flatbuffers::FlatBufferBuilder &_fbb) {
  MotorboatBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Wraith FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef WraithBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct WraithBuilder {
  typedef Wraith Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit WraithBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Wraith> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Wraith>(end);
    return o;
  }
};

inline flatbuffers::Offset<Wraith> CreateWraith(
    flatbuffers::FlatBufferBuilder &_fbb) {
  WraithBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Rubberboat FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef RubberboatBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct RubberboatBuilder {
  typedef Rubberboat Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit RubberboatBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Rubberboat> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Rubberboat>(end);
    return o;
  }
};

inline flatbuffers::Offset<Rubberboat> CreateRubberboat(
    flatbuffers::FlatBufferBuilder &_fbb) {
  RubberboatBuilder builder_(_fbb);
  return builder_.Finish();
}

struct Pushable FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef PushableBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PREVIOUS_TRIGGER_FLAGS = 4,
    VT_PUSHABLE_BEHAVIOUR_STATE = 6,
    VT_PUSHABLE_GRAVITY = 8,
    VT_PUSHABLE_WATER_FORCE = 10,
    VT_PUSHABLE_STACK_LIMIT = 12,
    VT_PUSHABLE_STACK_UPPER = 14,
    VT_PUSHABLE_STACK_LOWER = 16,
    VT_PUSHABLE_START_X = 18,
    VT_PUSHABLE_START_Z = 20,
    VT_PUSHABLE_ROOM_NUMBER = 22,
    VT_PUSHABLE_COLLIDER_FLAG = 24,
    VT_PUSHABLE_NORTH_PULLABLE = 26,
    VT_PUSHABLE_NORTH_PUSHABLE = 28,
    VT_PUSHABLE_NORTH_CLIMBABLE = 30,
    VT_PUSHABLE_EAST_PULLABLE = 32,
    VT_PUSHABLE_EAST_PUSHABLE = 34,
    VT_PUSHABLE_EAST_CLIMBABLE = 36,
    VT_PUSHABLE_SOUTH_PULLABLE = 38,
    VT_PUSHABLE_SOUTH_PUSHABLE = 40,
    VT_PUSHABLE_SOUTH_CLIMBABLE = 42,
    VT_PUSHABLE_WEST_PULLABLE = 44,
    VT_PUSHABLE_WEST_PUSHABLE = 46,
    VT_PUSHABLE_WEST_CLIMBABLE = 48
  };
  int32_t previous_trigger_flags() const {
    return GetField<int32_t>(VT_PREVIOUS_TRIGGER_FLAGS, 0);
  }
  int32_t pushable_behaviour_state() const {
    return GetField<int32_t>(VT_PUSHABLE_BEHAVIOUR_STATE, 0);
  }
  float pushable_gravity() const {
    return GetField<float>(VT_PUSHABLE_GRAVITY, 0.0f);
  }
  float pushable_water_force() const {
    return GetField<float>(VT_PUSHABLE_WATER_FORCE, 0.0f);
  }
  int32_t pushable_stack_limit() const {
    return GetField<int32_t>(VT_PUSHABLE_STACK_LIMIT, 0);
  }
  int32_t pushable_stack_upper() const {
    return GetField<int32_t>(VT_PUSHABLE_STACK_UPPER, 0);
  }
  int32_t pushable_stack_lower() const {
    return GetField<int32_t>(VT_PUSHABLE_STACK_LOWER, 0);
  }
  int32_t pushable_start_x() const {
    return GetField<int32_t>(VT_PUSHABLE_START_X, 0);
  }
  int32_t pushable_start_z() const {
    return GetField<int32_t>(VT_PUSHABLE_START_Z, 0);
  }
  int32_t pushable_room_number() const {
    return GetField<int32_t>(VT_PUSHABLE_ROOM_NUMBER, 0);
  }
  bool pushable_collider_flag() const {
    return GetField<uint8_t>(VT_PUSHABLE_COLLIDER_FLAG, 0) != 0;
  }
  bool pushable_north_pullable() const {
    return GetField<uint8_t>(VT_PUSHABLE_NORTH_PULLABLE, 0) != 0;
  }
  bool pushable_north_pushable() const {
    return GetField<uint8_t>(VT_PUSHABLE_NORTH_PUSHABLE, 0) != 0;
  }
  bool pushable_north_climbable() const {
    return GetField<uint8_t>(VT_PUSHABLE_NORTH_CLIMBABLE, 0) != 0;
  }
  bool pushable_east_pullable() const {
    return GetField<uint8_t>(VT_PUSHABLE_EAST_PULLABLE, 0) != 0;
  }
  bool pushable_east_pushable() const {
    return GetField<uint8_t>(VT_PUSHABLE_EAST_PUSHABLE, 0) != 0;
  }
  bool pushable_east_climbable() const {
    return GetField<uint8_t>(VT_PUSHABLE_EAST_CLIMBABLE, 0) != 0;
  }
  bool pushable_south_pullable() const {
    return GetField<uint8_t>(VT_PUSHABLE_SOUTH_PULLABLE, 0) != 0;
  }
  bool pushable_south_pushable() const {
    return GetField<uint8_t>(VT_PUSHABLE_SOUTH_PUSHABLE, 0) != 0;
  }
  bool pushable_south_climbable() const {
    return GetField<uint8_t>(VT_PUSHABLE_SOUTH_CLIMBABLE, 0) != 0;
  }
  bool pushable_west_pullable() const {
    return GetField<uint8_t>(VT_PUSHABLE_WEST_PULLABLE, 0) != 0;
  }
  bool pushable_west_pushable() const {
    return GetField<uint8_t>(VT_PUSHABLE_WEST_PUSHABLE, 0) != 0;
  }
  bool pushable_west_climbable() const {
    return GetField<uint8_t>(VT_PUSHABLE_WEST_CLIMBABLE, 0) != 0;
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_PREVIOUS_TRIGGER_FLAGS) &&
           VerifyField<int32_t>(verifier, VT_PUSHABLE_BEHAVIOUR_STATE) &&
           VerifyField<float>(verifier, VT_PUSHABLE_GRAVITY) &&
           VerifyField<float>(verifier, VT_PUSHABLE_WATER_FORCE) &&
           VerifyField<int32_t>(verifier, VT_PUSHABLE_STACK_LIMIT) &&
           VerifyField<int32_t>(verifier, VT_PUSHABLE_STACK_UPPER) &&
           VerifyField<int32_t>(verifier, VT_PUSHABLE_STACK_LOWER) &&
           VerifyField<int32_t>(verifier, VT_PUSHABLE_START_X) &&
           VerifyField<int32_t>(verifier, VT_PUSHABLE_START_Z) &&
           VerifyField<int32_t>(verifier, VT_PUSHABLE_ROOM_NUMBER) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_COLLIDER_FLAG) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_NORTH_PULLABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_NORTH_PUSHABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_NORTH_CLIMBABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_EAST_PULLABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_EAST_PUSHABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_EAST_CLIMBABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_SOUTH_PULLABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_SOUTH_PUSHABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_SOUTH_CLIMBABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_WEST_PULLABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_WEST_PUSHABLE) &&
           VerifyField<uint8_t>(verifier, VT_PUSHABLE_WEST_CLIMBABLE) &&
           verifier.EndTable();
  }
};

struct PushableBuilder {
  typedef Pushable Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_previous_trigger_flags(int32_t previous_trigger_flags) {
    fbb_.AddElement<int32_t>(Pushable::VT_PREVIOUS_TRIGGER_FLAGS, previous_trigger_flags, 0);
  }
  void add_pushable_behaviour_state(int32_t pushable_behaviour_state) {
    fbb_.AddElement<int32_t>(Pushable::VT_PUSHABLE_BEHAVIOUR_STATE, pushable_behaviour_state, 0);
  }
  void add_pushable_gravity(float pushable_gravity) {
    fbb_.AddElement<float>(Pushable::VT_PUSHABLE_GRAVITY, pushable_gravity, 0.0f);
  }
  void add_pushable_water_force(float pushable_water_force) {
    fbb_.AddElement<float>(Pushable::VT_PUSHABLE_WATER_FORCE, pushable_water_force, 0.0f);
  }
  void add_pushable_stack_limit(int32_t pushable_stack_limit) {
    fbb_.AddElement<int32_t>(Pushable::VT_PUSHABLE_STACK_LIMIT, pushable_stack_limit, 0);
  }
  void add_pushable_stack_upper(int32_t pushable_stack_upper) {
    fbb_.AddElement<int32_t>(Pushable::VT_PUSHABLE_STACK_UPPER, pushable_stack_upper, 0);
  }
  void add_pushable_stack_lower(int32_t pushable_stack_lower) {
    fbb_.AddElement<int32_t>(Pushable::VT_PUSHABLE_STACK_LOWER, pushable_stack_lower, 0);
  }
  void add_pushable_start_x(int32_t pushable_start_x) {
    fbb_.AddElement<int32_t>(Pushable::VT_PUSHABLE_START_X, pushable_start_x, 0);
  }
  void add_pushable_start_z(int32_t pushable_start_z) {
    fbb_.AddElement<int32_t>(Pushable::VT_PUSHABLE_START_Z, pushable_start_z, 0);
  }
  void add_pushable_room_number(int32_t pushable_room_number) {
    fbb_.AddElement<int32_t>(Pushable::VT_PUSHABLE_ROOM_NUMBER, pushable_room_number, 0);
  }
  void add_pushable_collider_flag(bool pushable_collider_flag) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_COLLIDER_FLAG, static_cast<uint8_t>(pushable_collider_flag), 0);
  }
  void add_pushable_north_pullable(bool pushable_north_pullable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_NORTH_PULLABLE, static_cast<uint8_t>(pushable_north_pullable), 0);
  }
  void add_pushable_north_pushable(bool pushable_north_pushable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_NORTH_PUSHABLE, static_cast<uint8_t>(pushable_north_pushable), 0);
  }
  void add_pushable_north_climbable(bool pushable_north_climbable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_NORTH_CLIMBABLE, static_cast<uint8_t>(pushable_north_climbable), 0);
  }
  void add_pushable_east_pullable(bool pushable_east_pullable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_EAST_PULLABLE, static_cast<uint8_t>(pushable_east_pullable), 0);
  }
  void add_pushable_east_pushable(bool pushable_east_pushable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_EAST_PUSHABLE, static_cast<uint8_t>(pushable_east_pushable), 0);
  }
  void add_pushable_east_climbable(bool pushable_east_climbable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_EAST_CLIMBABLE, static_cast<uint8_t>(pushable_east_climbable), 0);
  }
  void add_pushable_south_pullable(bool pushable_south_pullable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_SOUTH_PULLABLE, static_cast<uint8_t>(pushable_south_pullable), 0);
  }
  void add_pushable_south_pushable(bool pushable_south_pushable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_SOUTH_PUSHABLE, static_cast<uint8_t>(pushable_south_pushable), 0);
  }
  void add_pushable_south_climbable(bool pushable_south_climbable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_SOUTH_CLIMBABLE, static_cast<uint8_t>(pushable_south_climbable), 0);
  }
  void add_pushable_west_pullable(bool pushable_west_pullable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_WEST_PULLABLE, static_cast<uint8_t>(pushable_west_pullable), 0);
  }
  void add_pushable_west_pushable(bool pushable_west_pushable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_WEST_PUSHABLE, static_cast<uint8_t>(pushable_west_pushable), 0);
  }
  void add_pushable_west_climbable(bool pushable_west_climbable) {
    fbb_.AddElement<uint8_t>(Pushable::VT_PUSHABLE_WEST_CLIMBABLE, static_cast<uint8_t>(pushable_west_climbable), 0);
  }
  explicit PushableBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Pushable> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Pushable>(end);
    return o;
  }
};

inline flatbuffers::Offset<Pushable> CreatePushable(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t previous_trigger_flags = 0,
    int32_t pushable_behaviour_state = 0,
    float pushable_gravity = 0.0f,
    float pushable_water_force = 0.0f,
    int32_t pushable_stack_limit = 0,
    int32_t pushable_stack_upper = 0,
    int32_t pushable_stack_lower = 0,
    int32_t pushable_start_x = 0,
    int32_t pushable_start_z = 0,
    int32_t pushable_room_number = 0,
    bool pushable_collider_flag = false,
    bool pushable_north_pullable = false,
    bool pushable_north_pushable = false,
    bool pushable_north_climbable = false,
    bool pushable_east_pullable = false,
    bool pushable_east_pushable = false,
    bool pushable_east_climbable = false,
    bool pushable_south_pullable = false,
    bool pushable_south_pushable = false,
    bool pushable_south_climbable = false,
    bool pushable_west_pullable = false,
    bool pushable_west_pushable = false,
    bool pushable_west_climbable = false) {
  PushableBuilder builder_(_fbb);
  builder_.add_pushable_room_number(pushable_room_number);
  builder_.add_pushable_start_z(pushable_start_z);
  builder_.add_pushable_start_x(pushable_start_x);
  builder_.add_pushable_stack_lower(pushable_stack_lower);
  builder_.add_pushable_stack_upper(pushable_stack_upper);
  builder_.add_pushable_stack_limit(pushable_stack_limit);
  builder_.add_pushable_water_force(pushable_water_force);
  builder_.add_pushable_gravity(pushable_gravity);
  builder_.add_pushable_behaviour_state(pushable_behaviour_state);
  builder_.add_previous_trigger_flags(previous_trigger_flags);
  builder_.add_pushable_west_climbable(pushable_west_climbable);
  builder_.add_pushable_west_pushable(pushable_west_pushable);
  builder_.add_pushable_west_pullable(pushable_west_pullable);
  builder_.add_pushable_south_climbable(pushable_south_climbable);
  builder_.add_pushable_south_pushable(pushable_south_pushable);
  builder_.add_pushable_south_pullable(pushable_south_pullable);
  builder_.add_pushable_east_climbable(pushable_east_climbable);
  builder_.add_pushable_east_pushable(pushable_east_pushable);
  builder_.add_pushable_east_pullable(pushable_east_pullable);
  builder_.add_pushable_north_climbable(pushable_north_climbable);
  builder_.add_pushable_north_pushable(pushable_north_pushable);
  builder_.add_pushable_north_pullable(pushable_north_pullable);
  builder_.add_pushable_collider_flag(pushable_collider_flag);
  return builder_.Finish();
}

struct Minecart FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MinecartBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TURN_ROT = 4,
    VT_TURN_X = 6,
    VT_TURN_Z = 8,
    VT_TURN_LEN = 10,
    VT_VELOCITY = 12,
    VT_VERTICAL_VELOCITY = 14,
    VT_GRADIENT = 16,
    VT_STOP_DELAY = 18,
    VT_FLOOR_HEIGHT_MIDDLE = 20,
    VT_FLOOR_HEIGHT_FRONT = 22,
    VT_FLAGS = 24
  };
  int32_t turn_rot() const {
    return GetField<int32_t>(VT_TURN_ROT, 0);
  }
  int32_t turn_x() const {
    return GetField<int32_t>(VT_TURN_X, 0);
  }
  int32_t turn_z() const {
    return GetField<int32_t>(VT_TURN_Z, 0);
  }
  int32_t turn_len() const {
    return GetField<int32_t>(VT_TURN_LEN, 0);
  }
  int32_t velocity() const {
    return GetField<int32_t>(VT_VELOCITY, 0);
  }
  int32_t vertical_velocity() const {
    return GetField<int32_t>(VT_VERTICAL_VELOCITY, 0);
  }
  int32_t gradient() const {
    return GetField<int32_t>(VT_GRADIENT, 0);
  }
  int32_t stop_delay() const {
    return GetField<int32_t>(VT_STOP_DELAY, 0);
  }
  int32_t floor_height_middle() const {
    return GetField<int32_t>(VT_FLOOR_HEIGHT_MIDDLE, 0);
  }
  int32_t floor_height_front() const {
    return GetField<int32_t>(VT_FLOOR_HEIGHT_FRONT, 0);
  }
  int32_t flags() const {
    return GetField<int32_t>(VT_FLAGS, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_TURN_ROT) &&
           VerifyField<int32_t>(verifier, VT_TURN_X) &&
           VerifyField<int32_t>(verifier, VT_TURN_Z) &&
           VerifyField<int32_t>(verifier, VT_TURN_LEN) &&
           VerifyField<int32_t>(verifier, VT_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_VERTICAL_VELOCITY) &&
           VerifyField<int32_t>(verifier, VT_GRADIENT) &&
           VerifyField<int32_t>(verifier, VT_STOP_DELAY) &&
           VerifyField<int32_t>(verifier, VT_FLOOR_HEIGHT_MIDDLE) &&
           VerifyField<int32_t>(verifier, VT_FLOOR_HEIGHT_FRONT) &&
           VerifyField<int32_t>(verifier, VT_FLAGS) &&
           verifier.EndTable();
  }
};

struct MinecartBuilder {
  typedef Minecart Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_turn_rot(int32_t turn_rot) {
    fbb_.AddElement<int32_t>(Minecart::VT_TURN_ROT, turn_rot, 0);
  }
  void add_turn_x(int32_t turn_x) {
    fbb_.AddElement<int32_t>(Minecart::VT_TURN_X, turn_x, 0);
  }
  void add_turn_z(int32_t turn_z) {
    fbb_.AddElement<int32_t>(Minecart::VT_TURN_Z, turn_z, 0);
  }
  void add_turn_len(int32_t turn_len) {
    fbb_.AddElement<int32_t>(Minecart::VT_TURN_LEN, turn_len, 0);
  }
  void add_velocity(int32_t velocity) {
    fbb_.AddElement<int32_t>(Minecart::VT_VELOCITY, velocity, 0);
  }
  void add_vertical_velocity(int32_t vertical_velocity) {
    fbb_.AddElement<int32_t>(Minecart::VT_VERTICAL_VELOCITY, vertical_velocity, 0);
  }
  void add_gradient(int32_t gradient) {
    fbb_.AddElement<int32_t>(Minecart::VT_GRADIENT, gradient, 0);
  }
  void add_stop_delay(int32_t stop_delay) {
    fbb_.AddElement<int32_t>(Minecart::VT_STOP_DELAY, stop_delay, 0);
  }
  void add_floor_height_middle(int32_t floor_height_middle) {
    fbb_.AddElement<int32_t>(Minecart::VT_FLOOR_HEIGHT_MIDDLE, floor_height_middle, 0);
  }
  void add_floor_height_front(int32_t floor_height_front) {
    fbb_.AddElement<int32_t>(Minecart::VT_FLOOR_HEIGHT_FRONT, floor_height_front, 0);
  }
  void add_flags(int32_t flags) {
    fbb_.AddElement<int32_t>(Minecart::VT_FLAGS, flags, 0);
  }
  explicit MinecartBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<Minecart> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Minecart>(end);
    return o;
  }
};

inline flatbuffers::Offset<Minecart> CreateMinecart(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t turn_rot = 0,
    int32_t turn_x = 0,
    int32_t turn_z = 0,
    int32_t turn_len = 0,
    int32_t velocity = 0,
    int32_t vertical_velocity = 0,
    int32_t gradient = 0,
    int32_t stop_delay = 0,
    int32_t floor_height_middle = 0,
    int32_t floor_height_front = 0,
    int32_t flags = 0) {
  MinecartBuilder builder_(_fbb);
  builder_.add_flags(flags);
  builder_.add_floor_height_front(floor_height_front);
  builder_.add_floor_height_middle(floor_height_middle);
  builder_.add_stop_delay(stop_delay);
  builder_.add_gradient(gradient);
  builder_.add_vertical_velocity(vertical_velocity);
  builder_.add_velocity(velocity);
  builder_.add_turn_len(turn_len);
  builder_.add_turn_z(turn_z);
  builder_.add_turn_x(turn_x);
  builder_.add_turn_rot(turn_rot);
  return builder_.Finish();
}

struct LaraInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef LaraInfoBuilder Builder;
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           verifier.EndTable();
  }
};

struct LaraInfoBuilder {
  typedef LaraInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  explicit LaraInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<LaraInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<LaraInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<LaraInfo> CreateLaraInfo(
    flatbuffers::FlatBufferBuilder &_fbb) {
  LaraInfoBuilder builder_(_fbb);
  return builder_.Finish();
}

struct ItemNumber FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef ItemNumberBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NUM = 4
  };
  int16_t num() const {
    return GetField<int16_t>(VT_NUM, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int16_t>(verifier, VT_NUM) &&
           verifier.EndTable();
  }
};

struct ItemNumberBuilder {
  typedef ItemNumber Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_num(int16_t num) {
    fbb_.AddElement<int16_t>(ItemNumber::VT_NUM, num, 0);
  }
  explicit ItemNumberBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<ItemNumber> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ItemNumber>(end);
    return o;
  }
};

inline flatbuffers::Offset<ItemNumber> CreateItemNumber(
    flatbuffers::FlatBufferBuilder &_fbb,
    int16_t num = 0) {
  ItemNumberBuilder builder_(_fbb);
  builder_.add_num(num);
  return builder_.Finish();
}

struct FXInfo FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef FXInfoBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_COUNTER = 4,
    VT_FLAG1 = 6,
    VT_FLAG2 = 8
  };
  int32_t counter() const {
    return GetField<int32_t>(VT_COUNTER, 0);
  }
  int32_t flag1() const {
    return GetField<int32_t>(VT_FLAG1, 0);
  }
  int32_t flag2() const {
    return GetField<int32_t>(VT_FLAG2, 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_COUNTER) &&
           VerifyField<int32_t>(verifier, VT_FLAG1) &&
           VerifyField<int32_t>(verifier, VT_FLAG2) &&
           verifier.EndTable();
  }
};

struct FXInfoBuilder {
  typedef FXInfo Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_counter(int32_t counter) {
    fbb_.AddElement<int32_t>(FXInfo::VT_COUNTER, counter, 0);
  }
  void add_flag1(int32_t flag1) {
    fbb_.AddElement<int32_t>(FXInfo::VT_FLAG1, flag1, 0);
  }
  void add_flag2(int32_t flag2) {
    fbb_.AddElement<int32_t>(FXInfo::VT_FLAG2, flag2, 0);
  }
  explicit FXInfoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  flatbuffers::Offset<FXInfo> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<FXInfo>(end);
    return o;
  }
};

inline flatbuffers::Offset<FXInfo> CreateFXInfo(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t counter = 0,
    int32_t flag1 = 0,
    int32_t flag2 = 0) {
  FXInfoBuilder builder_(_fbb);
  builder_.add_flag2(flag2);
  builder_.add_flag1(flag1);
  builder_.add_counter(counter);
  return builder_.Finish();
}

inline bool VerifyItemData(flatbuffers::Verifier &verifier, const void *obj, ItemData type) {
  switch (type) {
    case ItemData_NONE: {
      return true;
    }
    case ItemData_Int: {
      auto ptr = reinterpret_cast<const TEN::Save::Int *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Short: {
      auto ptr = reinterpret_cast<const TEN::Save::Short *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Float: {
      auto ptr = reinterpret_cast<const TEN::Save::Float *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_ShortArray: {
      auto ptr = reinterpret_cast<const TEN::Save::ShortArray *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_ItemNumber: {
      auto ptr = reinterpret_cast<const TEN::Save::ItemNumber *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Creature: {
      auto ptr = reinterpret_cast<const TEN::Save::Creature *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_LaserHead: {
      auto ptr = reinterpret_cast<const TEN::Save::LaserHead *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_QuadBike: {
      auto ptr = reinterpret_cast<const TEN::Save::QuadBike *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_BigGun: {
      auto ptr = reinterpret_cast<const TEN::Save::BigGun *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Motorbike: {
      auto ptr = reinterpret_cast<const TEN::Save::Motorbike *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Jeep: {
      auto ptr = reinterpret_cast<const TEN::Save::Jeep *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_LaraInfo: {
      auto ptr = reinterpret_cast<const TEN::Save::LaraInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Kayak: {
      auto ptr = reinterpret_cast<const TEN::Save::Kayak *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Door: {
      auto ptr = reinterpret_cast<const TEN::Save::Door *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Skidoo: {
      auto ptr = reinterpret_cast<const TEN::Save::Skidoo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_UPV: {
      auto ptr = reinterpret_cast<const TEN::Save::UPV *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Motorboat: {
      auto ptr = reinterpret_cast<const TEN::Save::Motorboat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Wraith: {
      auto ptr = reinterpret_cast<const TEN::Save::Wraith *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Rubberboat: {
      auto ptr = reinterpret_cast<const TEN::Save::Rubberboat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Pushable: {
      auto ptr = reinterpret_cast<const TEN::Save::Pushable *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_Minecart: {
      auto ptr = reinterpret_cast<const TEN::Save::Minecart *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case ItemData_FXInfo: {
      auto ptr = reinterpret_cast<const TEN::Save::FXInfo *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyItemDataVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyItemData(
        verifier,  values->Get(i), types->GetEnum<ItemData>(i))) {
      return false;
    }
  }
  return true;
}

}  // namespace Save
}  // namespace TEN

#endif  // FLATBUFFERS_GENERATED_TENITEMDATA_TEN_SAVE_H_
