--Weather presets --
-- ohne die ist die sonne zwischen den wolken nicht sichtbar

Flow.DefineWeatherPreset("ClearSky", 
{
    cloudB = {
     enabled        = true,
category             = "AltocumulusMid",
coverage		= 1.0,
    altoCloudAmount                 = 0.0,
	altoFbmGain                     = 0.0,
	  distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
	altoAbsorption                  = 0.0030,
	    blendThresholdHigh              = 0.0000,
    blendThresholdHighWidth         = 0.4000,
    blendThresholdLow               = 0.0000,
	    -- Technical tuning
    altoFbmScale                    = 0.6480,
    jitterStrength                  = 0.0000,
    altoJitterAbsCap                = 0.1000,
    upsampleSpatialSigma2           = 0.5000,
    temporalAlphaLow                = 0.0500,
    }
})

Flow.DefineWeatherPreset("Altocumulus", {
	duration ={6,9},-- {60,250},9	
	--nextPresetB = {ClearSkyLow = {1.0, 50}},
cloudB = {
    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 1.0000,
    density                         = 0.8000,
    bottomHeight                    = 2127,
    horizonWidth                    = 3252,
    altoHorizonWidth                = 0.0000,
    evolutionSpeed                  = 0.0000,
    horizonFade                     = 1.0000,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 1.0000,
    altoCovSoftWidth                = 0.2500,
    altoAbsorption                  = 0.0130,
    altoCloudSize                   = 0.2240,
    altoCloudAmount                 = 0.5920,
    altoCloudBrightness             = 0.6800,
    altoCloudColorR                 = 1.0000,
    altoCloudColorG                 = 1.0000,
    altoCloudColorB                 = 1.0000,
    altoCloudColorDarkR             = 0.3571,
    altoCloudColorDarkG             = 0.3571,
    altoCloudColorDarkB             = 0.4363,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.8630,
    altoThickness                   = 5000,
    altoBottomSoftness              = 0.9230,
    altoZenithBias                  = 0.0000,
    altoHeightBlendPower            = 1.0000,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 0.0000,
    -- Composite blend
    blendThresholdHigh              = 0.0723,
    blendThresholdHighWidth         = 0.4000,
    blendThresholdLow               = 0.0000,
    -- Lightning
    lightningEnabled                = false,
    lightningStrikeFreq             = 0.1000,
    lightningInternalFreq           = 0.5000,
    lightningSpeed                  = 2.5000,
    lightningInternalSpeed          = 5.0000,
    lightningGlowIntensity          = 3.0000,
    lightningFlashIntensity         = 4.0000,
    lightningBoltColorR             = 0.3000,
    lightningBoltColorG             = 0.6000,
    lightningBoltColorB             = 1.0000,
    lightningAmbientContrib         = 0.1500,
    lightningBoltLengthScale        = 1.0000,
    lightningBoltThicknessScale     = 1.0000,
    -- Technical tuning
    altoFbmScale                    = 0.5150,
    jitterStrength                  = 1.0000,
    altoJitterAbsCap                = 10.0000,
    upsampleSpatialSigma2           = 0.001,
    temporalAlphaLow                = 0.0500,
    temporalAlphaHigh               = 0.9500,
    }
})


Flow.DefineWeatherPreset("RainSnowOvercast", {
	duration ={6,9},-- {60,250},9	
	--nextPresetB = {Altocumulus = {1.0, 50}},
    cloudB = {

    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 1.0000,
    density                         = 10.0000,
    bottomHeight                    = 2127,
    horizonWidth                    = 1000,
    altoHorizonWidth                = 0.0000,
    evolutionSpeed                  = 1.0130,
    curlWarpStrength                = 1.0980,
    horizonFade                     = 1.0000,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 1.0000,
    altoCovSoftWidth                = 0.2500,
    altoAbsorption                  = 0.0130,
    altoCloudSize                   = 0.6140,
    altoCloudAmount                 = 1.0000,
    altoCloudBrightness             = 1.1230,
    altoCloudColorR                 = 1.0000,
    altoCloudColorG                 = 1.0000,
    altoCloudColorB                 = 1.0000,
    altoCloudColorDarkR             = 0.4699,
    altoCloudColorDarkG             = 0.4699,
    altoCloudColorDarkB             = 0.6029,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.7360,
    altoThickness                   = 5000,
    altoBottomSoftness              = 0.7130,
    altoZenithBias                  = 0.3180,
    altoHeightBlendPower            = 1.4440,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 1.0000,
    -- Composite blend
    blendThresholdHigh              = 0.500,
    blendThresholdHighWidth         = 4.000,
    blendThresholdLow               = 0.0040,
    -- Lightning
    lightningEnabled                = false,
    lightningStrikeFreq             = 0.1000,
    lightningInternalFreq           = 0.5000,
    lightningSpeed                  = 2.5000,
    lightningInternalSpeed          = 5.0000,
    lightningGlowIntensity          = 3.0000,
    lightningFlashIntensity         = 4.0000,
    lightningBoltColorR             = 0.3000,
    lightningBoltColorG             = 0.6000,
    lightningBoltColorB             = 1.0000,
    lightningAmbientContrib         = 0.1500,
    lightningBoltLengthScale        = 1.0000,
    lightningBoltThicknessScale     = 1.0000,
    -- Technical tuning
    altoFbmScale                    = 0.6110,
    jitterStrength                  = 1.0000,
    altoJitterAbsCap                = 0.1000,
    upsampleSpatialSigma2           = 0.5000,
    temporalAlphaLow                = 0.0000,
    temporalAlphaHigh               = 1.0000,


  
    }
})

Flow.DefineWeatherPreset("StormBuildUp", 
{
    highLayerLeadFraction = 0.2,
	duration = {6,9},--{120,360},
	--nextPresetA = {ClearSkyHigh = {1.0, 50}},
	--nextPresetB = { ClearSkyLow = {0.3, 60}, StormTransformation = {0.7, 90}},
	    cloudB = {
		enabled        		 = true,
		coverage		= 1.0,
        category       		 = "AltocumulusMid",
       	bottomHeight         = 2127,
		horizonWidth		 = 0.059,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.787,
        distanceFade         = 0.205,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.225,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.053,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.585,
        altoCloudColorDarkG  = 0.636,
        altoCloudColorDarkB  = 0.760,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.506,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.769,
		altoZenithBias		 = 1.0,
		altoHeightBlendPower =  2.637,	
		blendThresholdHigh = 0.010,
		blendThresholdLow  = 0.000,		
    }
})



Flow.DefineWeatherPreset("Thunderstorm", {
	duration = {6,9},--{230,560},
	--nextPresetB = {Altocumulus = {0.7, 60}, RainSnowOvercast = {0.3, 90}},
    cloudB = {
    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 1.0000,
    density                         = 0.8000,
    bottomHeight                    = 2127,
    horizonWidth                    = 100,
    altoHorizonWidth                = 0.0000,
    evolutionSpeed                  = 0.2760,
    curlWarpStrength                = 1.0000,
    horizonFade                     = 0.7240,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 0.0000,
    altoCovSoftWidth                = 0.2500,
    altoAbsorption                  = 0.1000,
    altoCloudSize                   = 0.2240,
    altoCloudAmount                 = 0.5940,
    altoCloudBrightness             = 0.4010,
    altoCloudColorR                 = 1.0000,
    altoCloudColorG                 = 1.0000,
    altoCloudColorB                 = 1.0000,
    altoCloudColorDarkR             = 0.1300,
    altoCloudColorDarkG             = 0.1300,
    altoCloudColorDarkB             = 0.1720,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.5910,
    altoThickness                   = 5000,
    altoBottomSoftness              = 0.7450,
    altoZenithBias                  = 0.0000,
    altoHeightBlendPower            = 4.0000,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 1.0000,
    -- Composite blend
    blendThresholdHigh              = 1.0000,
    blendThresholdHighWidth         = 0.0500,
    blendThresholdLow               = 0.0040,
    -- Lightning
    lightningEnabled                = true,
    lightningStrikeFreq             = 1.0000,
    lightningInternalFreq           = 0.1990,
    lightningSpeed                  = 1.2490,
    lightningInternalSpeed          = 3.1160,
    lightningGlowIntensity          = 5.0000,
    lightningFlashIntensity         = 5.0000,
    lightningBoltColorR             = 0.3630,
    lightningBoltColorG             = 0.3030,
    lightningBoltColorB             = 0.9800,
    lightningAmbientContrib         = 0.3220,
    lightningBoltLengthScale        = 1.6300,
    lightningBoltThicknessScale     = 0.6660,
    -- Technical tuning
    altoFbmScale                    = 2.0320,
    jitterStrength                  = 0.3000,
    altoJitterAbsCap                = 5.0000,
    upsampleSpatialSigma2           = 0.7500,
    temporalAlphaLow                = 0.0500,
    temporalAlphaHigh               = 0.9500,
	}
})


Flow.DefineWeatherPreset("Cirrustratus", {
	duration = {6,9},--{300, 560},
	--nextPresetB  = {ClearSkyHigh = {0.5, 0.3, 40}, AuroraBorealis = {0.0, 0.3, 25}, Cirrustratus = {0.5, 0.7, 25}},	  
	cloudB = 
	{
    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 0.8460,
    bottomHeight                    = 2127,
    horizonWidth                    = 384,
    altoHorizonWidth                = 0.0000,
    evolutionSpeed                  = 1.2760,
    curlWarpStrength                = 1.0000,
    horizonFade                     = 1.0000,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 0.4580,
    altoCovSoftWidth                = 0.1650,
    altoAbsorption                  = 0.1000,
    altoCloudSize                   = 0.4120,
    altoCloudAmount                 = 0.4510,
    altoCloudBrightness             = 0.9230,
    altoCloudColorR                 = 1.0000,
    altoCloudColorG                 = 1.0000,
    altoCloudColorB                 = 1.0000,
    altoCloudColorDarkR             = 0.6762,
    altoCloudColorDarkG             = 0.6762,
    altoCloudColorDarkB             = 0.8468,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.9000,
    altoThickness                   = 4343,
    altoBottomSoftness              = 0.2540,
    altoZenithBias                  = 0.0000,
    altoHeightBlendPower            = 1.0000,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 0.0000,
    -- Composite blend
    blendThresholdHigh              = 0.5275,
    blendThresholdHighWidth         = 0.3489,
    blendThresholdLow               = 0.0125,
    -- Lightning
    lightningEnabled                = false,
    lightningStrikeFreq             = 0.1000,
    lightningInternalFreq           = 0.5000,
    lightningSpeed                  = 2.5000,
    lightningInternalSpeed          = 5.0000,
    lightningGlowIntensity          = 3.0000,
    lightningFlashIntensity         = 4.0000,
    lightningBoltColorR             = 0.3000,
    lightningBoltColorG             = 0.6000,
    lightningBoltColorB             = 1.0000,
    lightningAmbientContrib         = 0.1500,
    lightningBoltLengthScale        = 1.0000,
    lightningBoltThicknessScale     = 1.0000,
    -- Technical tuning
    altoFbmScale                    = 0.5270,
    jitterStrength                  = 0.3000,
    altoJitterAbsCap                = 5.0000,
    upsampleSpatialSigma2           = 0.7500,
    temporalAlphaLow                = 0.0500,
    temporalAlphaHigh               = 0.9500,

    }
})

Flow.DefineWeatherPreset("CirrocumulusLots", {
	duration = {6,9},--{300, 560},
	nextPresetA  = {CirrocumulusFew = {0.2, 0.6, 40}, AltocumulusHigh = {0.5, 0.0, 25}, Cirrustratus = {0.5, 0.4, 25}},	  
		cloudB = {

    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 1.0000,
    density                         = 0.8000,
    bottomHeight                    = 2127,
    horizonWidth                    = 1,
    altoHorizonWidth                = 0.0900,
    evolutionSpeed                  = 0.9260,
    curlWarpStrength                = 0.2800,
    horizonFade                     = 1.0000,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 0.2510,
    altoCovSoftWidth                = 0.2500,
    altoAbsorption                  = 0.0310,
    altoCloudSize                   = 1.6870,
    altoCloudAmount                 = 0.3490,
    altoCloudBrightness             = 1.0000,
    altoCloudColorR                 = 1.0000,
    altoCloudColorG                 = 1.0000,
    altoCloudColorB                 = 1.0000,
    altoCloudColorDarkR             = 0.6930,
    altoCloudColorDarkG             = 0.6930,
    altoCloudColorDarkB             = 0.8730,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.6580,
    altoThickness                   = 569,
    altoBottomSoftness              = 0.5110,
    altoZenithBias                  = 0.3920,
    altoHeightBlendPower            = 4.0000,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 0.0000,
    -- Composite blend
    blendThresholdHigh              = 0.0200,
    blendThresholdHighWidth         = 0.4000,
    blendThresholdLow               = 0.0000,
    -- Lightning
    lightningEnabled                = false,
    lightningStrikeFreq             = 0.1000,
    lightningInternalFreq           = 0.5000,
    lightningSpeed                  = 2.5000,
    lightningInternalSpeed          = 5.0000,
    lightningGlowIntensity          = 3.0000,
    lightningFlashIntensity         = 4.0000,
    lightningBoltColorR             = 0.3000,
    lightningBoltColorG             = 0.6000,
    lightningBoltColorB             = 0.9900,
    lightningAmbientContrib         = 0.1500,
    lightningBoltLengthScale        = 1.0000,
    lightningBoltThicknessScale     = 1.0000,
    -- Technical tuning
    altoFbmScale                    = 0.5000,
    jitterStrength                  = 0.0000,
    altoJitterAbsCap                = 0.1000,
    upsampleSpatialSigma2           = 0.5000,
    temporalAlphaLow                = 0.0500,
    temporalAlphaHigh               = 0.9500,



    }
})

Flow.DefineWeatherPreset("CirrocumulusFew", {
	duration = {6,9},--{300, 560},
	--nextPresetA  = {FewToClearSky = {0.2, 0.6, 40}, StormBuildUpHigh = {0.5, 0.0, 90}, CirrocumulusLots = {0.3, 0.2, 50}, AuroraBorealis = {0.0, 0.2, 50}},	  
	cloudB = {
    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 1.0000,
    density                         = 0.8000,
    bottomHeight                    = 2127,
    horizonWidth                    = 1,
    altoHorizonWidth                = 0.0000,
    evolutionSpeed                  = 0.0000,
    curlWarpStrength                = 0.3010,
    horizonFade                     = 1.0000,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 0.0000,
    altoCovSoftWidth                = 0.2500,
	altoAbsorption                  = 0.0310,
    altoCloudSize                   = 1.6710,
    altoCloudAmount                 = 0.4880,
    altoCloudBrightness             = 1.3520,
    altoCloudColorR                 = 0.6960,
    altoCloudColorG                 = 0.6960,
    altoCloudColorB                 = 0.6960,
    altoCloudColorDarkR             = 0.3480,
    altoCloudColorDarkG             = 0.3480,
    altoCloudColorDarkB             = 0.3480,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.4340,
    altoThickness                   = 4209,
    altoBottomSoftness              = 0.8470,
    altoZenithBias                  = 0.6540,
    altoHeightBlendPower            = 1.4440,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 0.0000,
    -- Composite blend
    blendThresholdHigh              = 0.0000,
    blendThresholdHighWidth         = 0.4000,
    blendThresholdLow               = 0.0000,
    -- Lightning
    lightningEnabled                = false,
    lightningStrikeFreq             = 0.1000,
    lightningInternalFreq           = 0.5000,
    lightningSpeed                  = 2.5000,
    lightningInternalSpeed          = 5.0000,
    lightningGlowIntensity          = 3.0000,
    lightningFlashIntensity         = 4.0000,
    lightningBoltColorR             = 0.3000,
    lightningBoltColorG             = 0.6000,
    lightningBoltColorB             = 1.0000,
    lightningAmbientContrib         = 0.1500,
    lightningBoltLengthScale        = 1.0000,
    lightningBoltThicknessScale     = 1.0000,
    -- Technical tuning
    altoFbmScale                    = 0.6480,
    jitterStrength                  = 0.0000,
    altoJitterAbsCap                = 0.1000,
    upsampleSpatialSigma2           = 0.5000,
    temporalAlphaLow                = 0.0500,
    temporalAlphaHigh               = 0.9500,
    }
})

Flow.DefineWeatherPreset("CloudsTransformation", {
	duration = 30,--{300, 560},
    cloudB = {
	enabled        = true,
	category       = "AltocumulusMid",
    }
})
