--Weather presets --
-- ohne die ist die sonne zwischen den wolken nicht sichtbar

Flow.DefineWeatherPreset("ClearSky", 
{
	duration = 1,
	--nextPresetA  = {ClearSkyHigh = {1.0, 1.0, 1}},
	--nextPresetB  = {ClearSkyLow = {1.0, 1.0, 1}},	
    cloudA = {
		enabled        = false,
		coverage		= 0.0,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 2500,
		horizonWidth		 = 0,   -- 
        evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.458,
        altoCovSoftWidth     = 0.1650,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.412,
        altoCloudAmount      = 0.451,
        altoCloudBrightness  = 0.769,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.693,
        altoCloudColorDarkG  = 0.693,
        altoCloudColorDarkB  = 0.873,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.587,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.153,
		altoZenithBias		 = 1.000,
		altoHeightBlendPower = 1.564,
    },
	    cloudB = {
        enabled        = false,
category             = "AltocumulusMid",
quality = "Medium",
coverage		= 0.0,
        bottomHeight         = 2127,
		horizonWidth		 = 3252,
		evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 1.0,
        altoCovSoftWidth     = 0.2500,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.509,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.034,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.55,
        altoCloudColorDarkG  = 0.55,
        altoCloudColorDarkB  = 0.65,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.687,
        altoThickness        = 1480,
        altoBottomSoftness   = 1.0,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower =  1.000,
    }
})

Flow.DefineWeatherPreset("Altocumulus", {
	duration ={6,9},-- {60,250},9	
	--nextPresetB = {ClearSkyLow = {1.0, 50}},
cloudB = {
    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 1.0000,
    density                         = 0.8000,
    bottomHeight                    = 2127,
    horizonWidth                    = 3252,
    altoHorizonWidth                = 0.0000,
    evolutionSpeed                  = 0.0000,
    horizonFade                     = 1.0000,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 1.0000,
    altoCovSoftWidth                = 0.2500,
    altoAbsorption                  = 0.0130,
    altoCloudSize                   = 0.2240,
    altoCloudAmount                 = 0.5920,
    altoCloudBrightness             = 0.6800,
    altoCloudColorR                 = 1.0000,
    altoCloudColorG                 = 1.0000,
    altoCloudColorB                 = 1.0000,
    altoCloudColorDarkR             = 0.3571,
    altoCloudColorDarkG             = 0.3571,
    altoCloudColorDarkB             = 0.4363,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.8630,
    altoThickness                   = 5000,
    altoBottomSoftness              = 0.9230,
    altoZenithBias                  = 0.0000,
    altoHeightBlendPower            = 1.0000,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 0.0000,
    -- Composite blend
    blendThresholdHigh              = 0.0723,
    blendThresholdHighWidth         = 0.4000,
    blendThresholdLow               = 0.0000,
    -- Lightning
    lightningEnabled                = false,
    lightningStrikeFreq             = 0.1000,
    lightningInternalFreq           = 0.5000,
    lightningSpeed                  = 2.5000,
    lightningInternalSpeed          = 5.0000,
    lightningGlowIntensity          = 3.0000,
    lightningFlashIntensity         = 4.0000,
    lightningBoltColorR             = 0.3000,
    lightningBoltColorG             = 0.6000,
    lightningBoltColorB             = 1.0000,
    lightningAmbientContrib         = 0.1500,
    lightningBoltLengthScale        = 1.0000,
    lightningBoltThicknessScale     = 1.0000,
    -- Technical tuning
    altoFbmScale                    = 0.5150,
    jitterStrength                  = 1.0000,
    altoJitterAbsCap                = 10.0000,
    upsampleSpatialSigma2           = 0.5000,
    temporalAlphaLow                = 0.0500,
    temporalAlphaHigh               = 0.9500,
    }
})

Flow.DefineWeatherPreset("CirrocumulusClear", {

	duration = 1,-- {60,250},9	
	--nextPresetB = {ClearSkyHigh = {1.0, 50}},
    cloudB = {
		enabled        = true,
		coverage		= 0.0,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 1536,
		horizonWidth		 = 0,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 1.621,
        altoCloudAmount      = 0.356,
        altoCloudBrightness  = 1.000,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.693,
        altoCloudColorDarkG  = 0.693,
        altoCloudColorDarkB  = 0.873,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.500,
        altoThickness        = 1004,
        altoBottomSoftness   = 0.941,
		altoZenithBias		 = 0.161,
		altoHeightBlendPower = 1.0,
			blendThresholdHigh = 0.034,
		blendThresholdLow  = 0.004,
    }
})

Flow.DefineWeatherPreset("RainSnowOvercast", {
	duration ={6,9},-- {60,250},9	
	--nextPresetB = {Altocumulus = {1.0, 50}},
    cloudB = {
        enabled              = true,
        category             = "AltocumulusMid",
		quality = "Medium",
		coverage		= 1.0,
        bottomHeight         = 4061,
		horizonWidth		 = 1000,
        evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.1,
        altoCloudSize        = 0.317,
        altoCloudAmount      = 0.799,
        altoCloudBrightness  = 0.932,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.55,
        altoCloudColorDarkG  = 0.55,
        altoCloudColorDarkB  = 0.65,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.401,
        altoThickness        = 5000,
        altoBottomSoftness   = 1.0,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower =  1.000,
		blendThresholdHigh = 1.000,
		blendThresholdLow  = 0.004,
    }
})

Flow.DefineWeatherPreset("StormBuildUp", 
{
    highLayerLeadFraction = 0.2,
	duration = {6,9},--{120,360},
	--nextPresetA = {ClearSkyHigh = {1.0, 50}},
	--nextPresetB = { ClearSkyLow = {0.3, 60}, StormTransformation = {0.7, 90}},
	    cloudB = {
		enabled        		 = true,
		coverage		= 1.0,
        category       		 = "AltocumulusMid",
		quality = "Medium",
       	bottomHeight         = 2663,
		horizonWidth		 = 0.059,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.787,
        distanceFade         = 0.205,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.225,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.053,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.585,
        altoCloudColorDarkG  = 0.636,
        altoCloudColorDarkB  = 0.760,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.506,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.769,
		altoZenithBias		 = 1.0,
		altoHeightBlendPower =  2.637,	
		blendThresholdHigh = 0.010,
		blendThresholdLow  = 0.000,		
    }
})

Flow.DefineWeatherPreset("StormBuildUpHigh", --funktioniert noch nicht
{
	duration = {6,9},--{100, 240},
	--nextPresetA = {ClearSkyHigh = {1.0, 50}},
	--nextPresetB = { ClearSkyLow = {0.3, 60}, StormTransformation = {0.7, 90}},
	    cloudB = {
		enabled        		 = true,
		coverage		= 1.0,
        category       		 = "AltocumulusMid",
		quality = "Medium",
       	bottomHeight         = 2663,
		horizonWidth		 = 0.000,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.787,
        distanceFade         = 0.205,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.2281,
        altoAbsorption       = 0.528,
        altoCloudSize        = 0.225,
        altoCloudAmount      = 0.117,
        altoCloudBrightness  = 0.971,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.585,
        altoCloudColorDarkG  = 0.636,
        altoCloudColorDarkB  = 0.760,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.506,
        altoThickness        = 3356,
        altoBottomSoftness   = 0.224,
		altoZenithBias		 = 1.0,
		altoHeightBlendPower =  1.772,
		blendThresholdHigh = 1.000,
		blendThresholdLow  = 0.004,
		
    }
})

Flow.DefineWeatherPreset("StormTransformation", 
{
 	duration = 1,--{100, 240},
	cloudA = 
	{

	},
    cloudB = 
	{

    }
})

Flow.DefineWeatherPreset("Thunderstorm", {
	duration = {6,9},--{230,560},
	--nextPresetB = {Altocumulus = {0.7, 60}, RainSnowOvercast = {0.3, 90}},
    cloudB = {
		enabled        = true,
		coverage		= 1.0,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 2663,
		horizonWidth		 = 100,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.724,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.536,
        altoCloudAmount      = 0.594,
        altoCloudBrightness  = 0.401,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.130,
        altoCloudColorDarkG  = 0.130,
        altoCloudColorDarkB  = 0.172,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.591,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.745,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower = 4.0,
		lightningEnabled        = true,
		lightningStrikeFreq     = 1.0,
		lightningInternalFreq   = 0.423,
		lightningSpeed          = 1.557,
		lightningInternalSpeed  = 3.116,
		lightningGlowIntensity  = 5.0,
		lightningFlashIntensity  = 5.0,
		lightningBoltColorR     = 0.363,
		lightningBoltColorG     = 0.303,
		lightningBoltColorB     = 0.980,
		lightningAmbientContrib = 0.322,
		lightningBoltLengthScale = 1.63,
		lightningBoltThicknessScale = 1.732,
		blendThresholdHigh = 1.000,
		blendThresholdLow  = 0.004,
	}
})

Flow.DefineWeatherPreset("ClearSkyHigh", {
	duration = {6,9},--{300, 560},
	nextPresetA  = {AuroraBorealis = {0.0, 0.3, 25}},	
    cloudA = {
		
    }
})

Flow.DefineWeatherPreset("ClearSkyLow", {
	duration = {6,9},--{300, 560},
	--nextPresetB  = {StormBuildUp = {0.3, 0.0, 40}, AltocumulusHigh = {0.3, 0.3, 25}, ClearSkyLow = {0.4, 0.7, 25}},	
    cloudB = {
        enabled        = true,
		category             = "AltocumulusMid",
		quality = "Medium",
		coverage		= 0.0,
        bottomHeight         = 2127,
		horizonWidth		 = 3252,
       evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 1.0,
        altoCovSoftWidth     = 0.2500,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.509,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.034,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.55,
        altoCloudColorDarkG  = 0.55,
        altoCloudColorDarkB  = 0.65,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.0,
        altoThickness        = 1480,
        altoBottomSoftness   = 1.0,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower =  1.000,
				blendThresholdHigh = 0.038,
		blendThresholdLow  = 0.00,
    }
})

Flow.DefineWeatherPreset("Cirrustratus", {
	duration = {6,9},--{300, 560},
	--nextPresetA  = {ClearSkyHigh = {0.5, 0.3, 40}, AuroraBorealis = {0.0, 0.3, 25}, Cirrustratus = {0.5, 0.7, 25}},	  
	cloudA = 
	{
		enabled        = true,
		coverage		= 0.450,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 2500,
		horizonWidth		 = 0,
       evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.458,
        altoCovSoftWidth     = 0.1650,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.412,
        altoCloudAmount      = 0.451,
        altoCloudBrightness  = 0.769,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.693,
        altoCloudColorDarkG  = 0.693,
        altoCloudColorDarkB  = 0.873,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.853,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.153,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower = 1.0,
				blendThresholdHigh = 0.800,
		blendThresholdLow  = 0.00,
    },
	 cloudB = 
	{
		enabled        		 = false,
		coverage		= 1.0,
        category       		 = "AltocumulusMid",
		quality = "Medium",
       	bottomHeight         = 11028,
		horizonWidth		 = 0.184,   
        evolutionSpeed       = 1.276,
        horizonFade          = 0.836,
        distanceFade         = 0.278,
        altoBillowStrength   = 1.0,
        altoCovSoftWidth     = 0.1590,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.225,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.585,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.585,
        altoCloudColorDarkG  = 0.636,
        altoCloudColorDarkB  = 0.760,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.506,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.769,
		altoZenithBias		 = 1.0,
		altoHeightBlendPower =  1.924,
	}
})

Flow.DefineWeatherPreset("CirrocumulusLots", {
	duration = {6,9},--{300, 560},
	nextPresetA  = {CirrocumulusFew = {0.2, 0.6, 40}, AltocumulusHigh = {0.5, 0.0, 25}, Cirrustratus = {0.5, 0.4, 25}},	  
		cloudB = {
    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 1.0000,
    density                         = 0.8000,
    bottomHeight                    = 1536,
    horizonWidth                    = 1,
    altoHorizonWidth                = 0.0900,
    evolutionSpeed                  = 0.9260,
    curlWarpStrength                = 0.2800,
    horizonFade                     = 1.0000,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 0.0000,
    altoCovSoftWidth                = 0.2500,
    altoAbsorption                  = 0.2400,
    altoCloudSize                   = 1.6370,
    altoCloudAmount                 = 0.1430,
    altoCloudBrightness             = 1.0000,
    altoCloudColorR                 = 1.0000,
    altoCloudColorG                 = 1.0000,
    altoCloudColorB                 = 1.0000,
    altoCloudColorDarkR             = 0.6930,
    altoCloudColorDarkG             = 0.6930,
    altoCloudColorDarkB             = 0.8730,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.5720,
    altoThickness                   = 569,
    altoBottomSoftness              = 0.5110,
    altoZenithBias                  = 0.3920,
    altoHeightBlendPower            = 4.0000,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 0.0000,
    -- Composite blend
    blendThresholdHigh              = 0.0530,
    blendThresholdHighWidth         = 0.4000,
    blendThresholdLow               = 0.0000,
    -- Lightning
    lightningEnabled                = false,
    lightningStrikeFreq             = 0.1000,
    lightningInternalFreq           = 0.5000,
    lightningSpeed                  = 2.5000,
    lightningInternalSpeed          = 5.0000,
    lightningGlowIntensity          = 3.0000,
    lightningFlashIntensity         = 4.0000,
    lightningBoltColorR             = 0.3000,
    lightningBoltColorG             = 0.6000,
    lightningBoltColorB             = 0.9900,
    lightningAmbientContrib         = 0.1500,
    lightningBoltLengthScale        = 1.0000,
    lightningBoltThicknessScale     = 1.0000,
    -- Technical tuning
    altoFbmScale                    = 0.5000,
    jitterStrength                  = 1.0000,
    altoJitterAbsCap                = 0.1000,
    upsampleSpatialSigma2           = 8.0000,
    temporalAlphaLow                = 0.0500,
    temporalAlphaHigh               = 0.9500,

    }
})

Flow.DefineWeatherPreset("CirrocumulusFew", {
	duration = {6,9},--{300, 560},
	--nextPresetA  = {FewToClearSky = {0.2, 0.6, 40}, StormBuildUpHigh = {0.5, 0.0, 90}, CirrocumulusLots = {0.3, 0.2, 50}, AuroraBorealis = {0.0, 0.2, 50}},	  
	cloudB = {
    enabled                         = true,
    category                        = "AltocumulusMid",
    coverage                        = 1.0000,
    density                         = 0.8000,
    bottomHeight                    = 1536,
    horizonWidth                    = 1,
    altoHorizonWidth                = 0.0000,
    evolutionSpeed                  = 0.0000,
    curlWarpStrength                = 0.3010,
    horizonFade                     = 1.0000,
    distanceFade                    = 0.0000,
    horizonMeshBleed                = 0.0000,
    -- Altocumulus-specific
    altoBillowStrength              = 0.0000,
    altoCovSoftWidth                = 0.2500,
    altoAbsorption                  = 0.0300,
    altoCloudSize                   = 1.6710,
    altoCloudAmount                 = 0.4570,
    altoCloudBrightness             = 1.3520,
    altoCloudColorR                 = 0.6960,
    altoCloudColorG                 = 0.6960,
    altoCloudColorB                 = 0.6960,
    altoCloudColorDarkR             = 0.3480,
    altoCloudColorDarkG             = 0.3480,
    altoCloudColorDarkB             = 0.3480,
    altoFbmLacunarity               = 4.0000,
    altoFbmGain                     = 0.4340,
    altoThickness                   = 3361,
    altoBottomSoftness              = 0.4760,
    altoZenithBias                  = 0.3600,
    altoHeightBlendPower            = 1.4440,
    altoBleedDepth                  = 0.0000,
    altoHorizonGradientFade         = 0.0000,
    -- Composite blend
    blendThresholdHigh              = 0.0000,
    blendThresholdHighWidth         = 0.4000,
    blendThresholdLow               = 0.0000,
    -- Lightning
    lightningEnabled                = false,
    lightningStrikeFreq             = 0.1000,
    lightningInternalFreq           = 0.5000,
    lightningSpeed                  = 2.5000,
    lightningInternalSpeed          = 5.0000,
    lightningGlowIntensity          = 3.0000,
    lightningFlashIntensity         = 4.0000,
    lightningBoltColorR             = 0.3000,
    lightningBoltColorG             = 0.6000,
    lightningBoltColorB             = 1.0000,
    lightningAmbientContrib         = 0.1500,
    lightningBoltLengthScale        = 1.0000,
    lightningBoltThicknessScale     = 1.0000,
    -- Technical tuning
    altoFbmScale                    = 0.6480,
    jitterStrength                  = 0.0000,
    altoJitterAbsCap                = 0.1000,
    upsampleSpatialSigma2           = 0.5000,
    temporalAlphaLow                = 0.0500,
    temporalAlphaHigh               = 0.9500,
    }
})

Flow.DefineWeatherPreset("CloudsTransformation", {
	duration = 30,--{300, 560},
    cloudB = {
	enabled        = true,
	category       = "AltocumulusMid",
	quality = "Medium",
    }
})

Flow.DefineWeatherPreset("AltocumulusHigh", 
{
	duration = {6,9},--{300, 560},
	nextPresetA  = {StormBuildUpHigh = {0.5, 0.0, 90}, AltocumulusHigh = {0.5, 0.7, 40}},	  
    nextPresetB  = {RainSnowOvercast = {0.4, 0.3, 40}, AltocumulusHigh = {0.6, 0.7, 40}},
    cloudB = {
     
    }
})
