--Weather presets --
-- ohne die ist die sonne zwischen den wolken nicht sichtbar

Flow.DefineWeatherPreset("ClearSky", 
{
	duration = 1,
	--nextPresetA  = {ClearSkyHigh = {1.0, 1.0, 1}},
	--nextPresetB  = {ClearSkyLow = {1.0, 1.0, 1}},	
	    transformPreset = "CloudsTransformation",
	transformDuration = 35,
    cloudA = {
		enabled        = false,
		coverage		= 0.0,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 2500,
		horizonWidth		 = 0,   -- 
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.1678,
        evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.458,
        altoCovSoftWidth     = 0.1650,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.412,
        altoCloudAmount      = 0.451,
        altoCloudBrightness  = 0.769,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.693,
        altoCloudColorDarkG  = 0.693,
        altoCloudColorDarkB  = 0.873,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.587,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.153,
		altoZenithBias		 = 1.000,
		altoHeightBlendPower = 1.564,
    },
	    cloudB = {
        enabled        = false,
category             = "AltocumulusMid",
quality = "Medium",
coverage		= 0.0,
        bottomHeight         = 2127,
		horizonWidth		 = 3252,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.2423,
		evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 1.0,
        altoCovSoftWidth     = 0.2500,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.509,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.034,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.55,
        altoCloudColorDarkG  = 0.55,
        altoCloudColorDarkB  = 0.65,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.687,
        altoThickness        = 1480,
        altoBottomSoftness   = 1.0,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower =  1.000,
    }
})

Flow.DefineWeatherPreset("Altocumulus", {
	duration ={6,9},-- {60,250},9	
	--nextPresetB = {ClearSkyLow = {1.0, 50}},
	    transformPreset = "CloudsTransformation",
	transformDuration = 35,
cloudB = {
        enabled        = true,
category             = "AltocumulusMid",
quality = "Medium",
coverage		= 1.0,
        bottomHeight         = 2127,
		horizonWidth		 = 3252,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.2423,
        evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 1.0,
        altoCovSoftWidth     = 0.2500,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.425,
        altoCloudAmount      = 0.595,
        altoCloudBrightness  = 1.034,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.55,
        altoCloudColorDarkG  = 0.55,
        altoCloudColorDarkB  = 0.65,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.452,
        altoThickness        = 2276,
        altoBottomSoftness   = 0.0,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower =  1.000,
		blendThresholdHigh = 0.261,
		blendThresholdHighWidth = 0.4000,
		blendThresholdLow  = 0.00,
    }
})

Flow.DefineWeatherPreset("CirrocumulusClear", {

	duration = 1,-- {60,250},9	
	--nextPresetB = {ClearSkyHigh = {1.0, 50}},
	    transformPreset = "CloudsTransformation",
	transformDuration = 35,
    cloudB = {
		enabled        = true,
		coverage		= 0.0,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 1536,
		horizonWidth		 = 0,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.6464,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 1.621,
        altoCloudAmount      = 0.356,
        altoCloudBrightness  = 1.000,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.693,
        altoCloudColorDarkG  = 0.693,
        altoCloudColorDarkB  = 0.873,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.500,
        altoThickness        = 1004,
        altoBottomSoftness   = 0.941,
		altoZenithBias		 = 0.161,
		altoHeightBlendPower = 1.0,
			blendThresholdHigh = 0.034,
		blendThresholdLow  = 0.004,
    }
})

Flow.DefineWeatherPreset("RainSnowOvercast", {
	duration ={6,9},-- {60,250},9	
	--nextPresetB = {Altocumulus = {1.0, 50}},
	    transformPreset = "CloudsTransformation",
	transformDuration = 35,
    cloudB = {
        enabled              = true,
        category             = "AltocumulusMid",
		quality = "Medium",
		coverage		= 1.0,
        bottomHeight         = 4061,
		horizonWidth		 = 1000,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.6288,
        evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.1,
        altoCloudSize        = 0.317,
        altoCloudAmount      = 0.799,
        altoCloudBrightness  = 0.932,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.55,
        altoCloudColorDarkG  = 0.55,
        altoCloudColorDarkB  = 0.65,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.401,
        altoThickness        = 5000,
        altoBottomSoftness   = 1.0,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower =  1.000,
		blendThresholdHigh = 1.000,
		blendThresholdLow  = 0.004,
    }
})

Flow.DefineWeatherPreset("StormBuildUp", 
{
    highLayerLeadFraction = 0.2,
	duration = {6,9},--{120,360},
	--nextPresetA = {ClearSkyHigh = {1.0, 50}},
	--nextPresetB = { ClearSkyLow = {0.3, 60}, StormTransformation = {0.7, 90}},
	    cloudB = {
		enabled        		 = true,
		coverage		= 1.0,
        category       		 = "AltocumulusMid",
		quality = "Medium",
       	bottomHeight         = 2663,
		horizonWidth		 = 0.059,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.2236,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.787,
        distanceFade         = 0.205,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.225,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.053,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.585,
        altoCloudColorDarkG  = 0.636,
        altoCloudColorDarkB  = 0.760,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.506,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.769,
		altoZenithBias		 = 1.0,
		altoHeightBlendPower =  2.637,	
		blendThresholdHigh = 0.010,
		blendThresholdLow  = 0.000,		
    }
})

Flow.DefineWeatherPreset("StormBuildUpHigh", --funktioniert noch nicht
{
	duration = {6,9},--{100, 240},
	--nextPresetA = {ClearSkyHigh = {1.0, 50}},
	--nextPresetB = { ClearSkyLow = {0.3, 60}, StormTransformation = {0.7, 90}},
	    cloudB = {
		enabled        		 = true,
		coverage		= 1.0,
        category       		 = "AltocumulusMid",
		quality = "Medium",
       	bottomHeight         = 2663,
		horizonWidth		 = 0.000,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.2236,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.787,
        distanceFade         = 0.205,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.2281,
        altoAbsorption       = 0.528,
        altoCloudSize        = 0.225,
        altoCloudAmount      = 0.117,
        altoCloudBrightness  = 0.971,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.585,
        altoCloudColorDarkG  = 0.636,
        altoCloudColorDarkB  = 0.760,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.506,
        altoThickness        = 3356,
        altoBottomSoftness   = 0.224,
		altoZenithBias		 = 1.0,
		altoHeightBlendPower =  1.772,
		blendThresholdHigh = 1.000,
		blendThresholdLow  = 0.004,
		
    }
})

Flow.DefineWeatherPreset("StormTransformation", 
{
 	duration = 1,--{100, 240},
	cloudA = 
	{

	},
    cloudB = 
	{

    }
})

Flow.DefineWeatherPreset("Thunderstorm", {
	duration = {6,9},--{230,560},
	--nextPresetB = {Altocumulus = {0.7, 60}, RainSnowOvercast = {0.3, 90}},
	    transformPreset = "CloudsTransformation",
	transformDuration = 35,
    cloudB = {
		enabled        = true,
		coverage		= 1.0,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 2663,
		horizonWidth		 = 100,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.6288,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.724,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.536,
        altoCloudAmount      = 0.594,
        altoCloudBrightness  = 0.401,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.130,
        altoCloudColorDarkG  = 0.130,
        altoCloudColorDarkB  = 0.172,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.591,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.745,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower = 4.0,
		lightningEnabled        = true,
		lightningStrikeFreq     = 1.0,
		lightningInternalFreq   = 0.423,
		lightningSpeed          = 1.557,
		lightningInternalSpeed  = 3.116,
		lightningGlowIntensity  = 5.0,
		lightningFlashIntensity  = 5.0,
		lightningBoltColorR     = 0.363,
		lightningBoltColorG     = 0.303,
		lightningBoltColorB     = 0.980,
		lightningAmbientContrib = 0.322,
		lightningBoltLengthScale = 1.63,
		lightningBoltThicknessScale = 1.732,
		blendThresholdHigh = 1.000,
		blendThresholdLow  = 0.004,
	}
})

Flow.DefineWeatherPreset("ClearSkyHigh", {
	duration = {6,9},--{300, 560},
	nextPresetA  = {AuroraBorealis = {0.0, 0.3, 25}},	
    cloudA = {
		
    }
})

Flow.DefineWeatherPreset("ClearSkyLow", {
	duration = {6,9},--{300, 560},
	--nextPresetB  = {StormBuildUp = {0.3, 0.0, 40}, AltocumulusHigh = {0.3, 0.3, 25}, ClearSkyLow = {0.4, 0.7, 25}},	
    transformPreset = "CloudsTransformation",
	transformDuration = 35,
    cloudB = {
        enabled        = true,
		category             = "AltocumulusMid",
		quality = "Medium",
		coverage		= 0.0,
        bottomHeight         = 2127,
		horizonWidth		 = 3252,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.2423,
       evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 1.0,
        altoCovSoftWidth     = 0.2500,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.509,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.034,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.55,
        altoCloudColorDarkG  = 0.55,
        altoCloudColorDarkB  = 0.65,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.0,
        altoThickness        = 1480,
        altoBottomSoftness   = 1.0,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower =  1.000,
				blendThresholdHigh = 0.038,
		blendThresholdLow  = 0.00,
    }
})

Flow.DefineWeatherPreset("Cirrustratus", {
	duration = {6,9},--{300, 560},
	--nextPresetA  = {ClearSkyHigh = {0.5, 0.3, 40}, AuroraBorealis = {0.0, 0.3, 25}, Cirrustratus = {0.5, 0.7, 25}},	  
        transformPreset = "CloudsTransformation",
	transformDuration = 35,
	cloudA = 
	{
		enabled        = true,
		coverage		= 0.450,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 2500,
		horizonWidth		 = 0,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.1678,
       evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.458,
        altoCovSoftWidth     = 0.1650,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.412,
        altoCloudAmount      = 0.451,
        altoCloudBrightness  = 0.769,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.693,
        altoCloudColorDarkG  = 0.693,
        altoCloudColorDarkB  = 0.873,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.853,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.153,
		altoZenithBias		 = 0.0,
		altoHeightBlendPower = 1.0,
				blendThresholdHigh = 0.800,
		blendThresholdLow  = 0.00,
    },
	 cloudB = 
	{
		enabled        		 = false,
		coverage		= 1.0,
        category       		 = "AltocumulusMid",
		quality = "Medium",
       	bottomHeight         = 11028,
		horizonWidth		 = 0.184,   
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.3075,
        evolutionSpeed       = 1.276,
        horizonFade          = 0.836,
        distanceFade         = 0.278,
        altoBillowStrength   = 1.0,
        altoCovSoftWidth     = 0.1590,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.225,
        altoCloudAmount      = 0.0,
        altoCloudBrightness  = 1.585,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.585,
        altoCloudColorDarkG  = 0.636,
        altoCloudColorDarkB  = 0.760,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.506,
        altoThickness        = 5000,
        altoBottomSoftness   = 0.769,
		altoZenithBias		 = 1.0,
		altoHeightBlendPower =  1.924,
	}
})

Flow.DefineWeatherPreset("CirrocumulusLots", {
	duration = {6,9},--{300, 560},
	nextPresetA  = {CirrocumulusFew = {0.2, 0.6, 40}, AltocumulusHigh = {0.5, 0.0, 25}, Cirrustratus = {0.5, 0.4, 25}},	  
        --transformPreset = "CloudsTransformation",
	--transformDuration = 35,
		cloudB = {
		enabled        = true,
		coverage		= 1.0,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 1536,
		horizonWidth		 = 0.031,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.6464,
        evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 1.637,
        altoCloudAmount      = 0.276,
        altoCloudBrightness  = 1.0,
        altoCloudColorR      = 1.0,
        altoCloudColorG      = 1.0,
        altoCloudColorB      = 1.0,
        altoCloudColorDarkR  = 0.693,
        altoCloudColorDarkG  = 0.693,
        altoCloudColorDarkB  = 0.873,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.486,
        altoThickness        = 465,
        altoBottomSoftness   = 0.427,
		altoZenithBias		 = 0.490,
		altoHeightBlendPower = 1.552,
		blendThresholdHigh = 0.053,
		blendThresholdHighWidth = 0.4050,
		blendThresholdLow  = 0.00,
    }
})

Flow.DefineWeatherPreset("CirrocumulusFew", {
	duration = {6,9},--{300, 560},
	--nextPresetA  = {FewToClearSky = {0.2, 0.6, 40}, StormBuildUpHigh = {0.5, 0.0, 90}, CirrocumulusLots = {0.3, 0.2, 50}, AuroraBorealis = {0.0, 0.2, 50}},	  
        transformPreset = "CloudsTransformation",
	transformDuration = 35,
		cloudB = {
		enabled        = true,
		coverage		= 1.0,
        category       = "AltocumulusMid",
		quality = "Medium",
        bottomHeight         = 1536,
		horizonWidth		 = 0.045,
        windDirectionX       = 1,
        windDirectionY       = 0,
        windSpeed            = 0.2140,
        evolutionSpeed       = 1.276,
        horizonFade          = 1.0,
        distanceFade         = 0.0,
        altoBillowStrength   = 0.0,
        altoCovSoftWidth     = 0.25,
        altoAbsorption       = 0.100,
        altoCloudSize        = 0.932,
        altoCloudAmount      = 0.363,
        altoCloudBrightness  = 1.352,
        altoCloudColorR      = 0.696,
        altoCloudColorG      = 0.696,
        altoCloudColorB      = 0.696,
        altoCloudColorDarkR  = 0.348,
        altoCloudColorDarkG  = 0.348,
        altoCloudColorDarkB  = 0.348,
        altoFbmLacunarity    = 4.0,
        altoFbmGain          = 0.347,
        altoThickness        = 1942,
        altoBottomSoftness   = 0.217,
		altoZenithBias		 = 0.318,
		altoHeightBlendPower = 1.444,
		blendThresholdHigh = 0.000,
		blendThresholdHighWidth = 0.4050,
		blendThresholdLow  = 0.00,
    }
})

Flow.DefineWeatherPreset("CloudsTransformation", {
	duration = 30,--{300, 560},
    cloudB = {
	enabled        = true,
	category       = "AltocumulusMid",
	quality = "Medium",
    }
})

Flow.DefineWeatherPreset("AltocumulusHigh", 
{
	duration = {6,9},--{300, 560},
	nextPresetA  = {StormBuildUpHigh = {0.5, 0.0, 90}, AltocumulusHigh = {0.5, 0.7, 40}},	  
    nextPresetB  = {RainSnowOvercast = {0.4, 0.3, 40}, AltocumulusHigh = {0.6, 0.7, 40}},
    cloudB = {
     
    }
})